/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Cursor;
import javax.swing.JOptionPane;
import projeto.ClasseArrylist;
import projeto.JogoDao;
import projeto.Usuario;
import static telas.Perfil.usuario;


/**
 *
 * @author ewert
 */
public class Atualizar extends javax.swing.JFrame {

    private Usuario usuario;
    
    /**
     * Creates new form Atualizar
     */
    public Atualizar() {
        initComponents();
         this.setExtendedState(Atualizar.MAXIMIZED_BOTH);
        
        LabelAtualizarPressionando.setVisible(false);
        LabelSetaPressionando.setVisible(false);
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        
        CaixaNome.setText(usuario.getLogin().toUpperCase());
        CaixaIdade.setText(usuario.getIdade() + "");
        CaixaGenero.setText(usuario.getGenero().toUpperCase());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CaixaNome = new javax.swing.JTextField();
        CaixaIdade = new javax.swing.JTextField();
        CaixaGenero = new javax.swing.JTextField();
        CampoSenha1 = new javax.swing.JPasswordField();
        CampoSenha2 = new javax.swing.JPasswordField();
        LabelSetaPressionando = new javax.swing.JLabel();
        LabelAtualizarPressionando = new javax.swing.JLabel();
        LabelAtualizar = new javax.swing.JLabel();
        BotaoReturn = new javax.swing.JButton();
        BotaoAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        CaixaNome.setBackground(new java.awt.Color(255,255,255,0)
        );
        CaixaNome.setFont(new java.awt.Font("Charlemagne Std", 0, 18)); // NOI18N
        CaixaNome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        CaixaNome.setOpaque(false);
        CaixaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaNomeActionPerformed(evt);
            }
        });
        getContentPane().add(CaixaNome);
        CaixaNome.setBounds(550, 160, 400, 30);

        CaixaIdade.setBackground(new java.awt.Color(255,255,255,0)
        );
        CaixaIdade.setFont(new java.awt.Font("Charlemagne Std", 0, 18)); // NOI18N
        CaixaIdade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        CaixaIdade.setOpaque(false);
        CaixaIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaIdadeActionPerformed(evt);
            }
        });
        getContentPane().add(CaixaIdade);
        CaixaIdade.setBounds(550, 200, 80, 30);

        CaixaGenero.setBackground(new java.awt.Color(255,255,255,0)
        );
        CaixaGenero.setFont(new java.awt.Font("Charlemagne Std", 0, 18)); // NOI18N
        CaixaGenero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        CaixaGenero.setOpaque(false);
        CaixaGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaGeneroActionPerformed(evt);
            }
        });
        getContentPane().add(CaixaGenero);
        CaixaGenero.setBounds(580, 240, 210, 30);

        CampoSenha1.setBackground(new java.awt.Color(255,255,255,0)
        );
        CampoSenha1.setFont(new java.awt.Font("Charlemagne Std", 0, 18)); // NOI18N
        CampoSenha1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        CampoSenha1.setOpaque(false);
        CampoSenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoSenha1ActionPerformed(evt);
            }
        });
        getContentPane().add(CampoSenha1);
        CampoSenha1.setBounds(560, 280, 400, 30);

        CampoSenha2.setBackground(new java.awt.Color(255,255,255,0));
        CampoSenha2.setFont(new java.awt.Font("Charlemagne Std", 0, 18)); // NOI18N
        CampoSenha2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        CampoSenha2.setOpaque(false);
        CampoSenha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoSenha2ActionPerformed(evt);
            }
        });
        getContentPane().add(CampoSenha2);
        CampoSenha2.setBounds(570, 320, 390, 30);

        LabelSetaPressionando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta atualizar.png"))); // NOI18N
        LabelSetaPressionando.setText("jLabel2");
        LabelSetaPressionando.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(LabelSetaPressionando);
        LabelSetaPressionando.setBounds(0, 0, 1040, 720);

        LabelAtualizarPressionando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao atualizar tela.png"))); // NOI18N
        LabelAtualizarPressionando.setText("jLabel1");
        LabelAtualizarPressionando.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(LabelAtualizarPressionando);
        LabelAtualizarPressionando.setBounds(0, 0, 1080, 720);

        LabelAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atualizar-sem-tela-preta.gif"))); // NOI18N
        getContentPane().add(LabelAtualizar);
        LabelAtualizar.setBounds(0, 0, 1280, 720);

        BotaoReturn.setText("jButton1");
        BotaoReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoReturnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoReturnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoReturnMouseReleased(evt);
            }
        });
        BotaoReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoReturnActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoReturn);
        BotaoReturn.setBounds(20, 640, 73, 70);

        BotaoAtualizar.setText("jButton1");
        BotaoAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoAtualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoAtualizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoAtualizarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoAtualizarMouseReleased(evt);
            }
        });
        BotaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoAtualizar);
        BotaoAtualizar.setBounds(360, 590, 560, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAtualizarActionPerformed
        JogoDao jDAO = new JogoDao();
        int aux = 0;
        if(CampoSenha1.getText().equals("") || CampoSenha2.getText().equals("")) {
            JOptionPane.showMessageDialog(this,"Você precisa digitar uma senha e sua confirmação!");
        }
        else if(CampoSenha1.getText().equals(CampoSenha2.getText())) {
            
            for (int i=0;i<jDAO.getNomeUsuario().size();i++){
                
                if (CaixaNome.getText().equalsIgnoreCase(jDAO.getNomeUsuario().get(i))){
                    JOptionPane.showMessageDialog(this,"Este Nome/Login já existe. Por favor tente outro.");
                    aux++;
                }    
            
                
                }
                if (aux == 0){    
                    usuario.setLogin(CaixaNome.getText());
                    usuario.setSenha(CampoSenha1.getText());
                    usuario.setGenero(CaixaGenero.getText());
                    usuario.setIdade(CaixaIdade.getText());

                    jDAO.atualizar(usuario);
                    JOptionPane.showMessageDialog(this,"Atualizado com sucesso");
                }
            }    
        else {
            
        }
        

    }//GEN-LAST:event_BotaoAtualizarActionPerformed
    
    private void BotaoAtualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoAtualizarMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotaoAtualizarMouseEntered

    private void BotaoAtualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoAtualizarMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoAtualizarMouseExited

    private void BotaoAtualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoAtualizarMousePressed
        LabelAtualizarPressionando.setVisible(true);
    }//GEN-LAST:event_BotaoAtualizarMousePressed

    private void BotaoAtualizarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoAtualizarMouseReleased
        LabelAtualizarPressionando.setVisible(false);
    }//GEN-LAST:event_BotaoAtualizarMouseReleased

    private void BotaoReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
       
    }//GEN-LAST:event_BotaoReturnMouseEntered

    private void BotaoReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoReturnMouseExited

    private void BotaoReturnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMousePressed
        LabelSetaPressionando.setVisible(true);
    }//GEN-LAST:event_BotaoReturnMousePressed

    private void BotaoReturnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMouseReleased
        LabelSetaPressionando.setVisible(false);
    }//GEN-LAST:event_BotaoReturnMouseReleased

    private void CaixaIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaIdadeActionPerformed

    private void CaixaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaNomeActionPerformed

    private void CaixaGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaGeneroActionPerformed

    private void CampoSenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoSenha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoSenha1ActionPerformed

    private void CampoSenha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoSenha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoSenha2ActionPerformed

    private void BotaoReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoReturnActionPerformed
        Perfil perfil = new Perfil ();
        perfil.setUsuario(usuario);
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoReturnActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAtualizar;
    private javax.swing.JButton BotaoReturn;
    private javax.swing.JTextField CaixaGenero;
    private javax.swing.JTextField CaixaIdade;
    private javax.swing.JTextField CaixaNome;
    private javax.swing.JPasswordField CampoSenha1;
    private javax.swing.JPasswordField CampoSenha2;
    private javax.swing.JLabel LabelAtualizar;
    private javax.swing.JLabel LabelAtualizarPressionando;
    private javax.swing.JLabel LabelSetaPressionando;
    // End of variables declaration//GEN-END:variables
}
