/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Cursor;
import javax.swing.JOptionPane;
import projeto.Usuario;

/**
 *
 * @author ewert
 */
public class Avaliacao1 extends javax.swing.JFrame {
    private Usuario usuario;
   
    /**
     * Creates new form Avaliação
     */
    public Avaliacao1() {
        initComponents();
         this.setExtendedState(Avaliacao1.MAXIMIZED_BOTH);
        LabelSetaPressionada.setVisible(false);
        LabelBarPressionada.setVisible(false);
        LabelFarolPressionada.setVisible(false);
        LabelEspaçoPressionada.setVisible(false);
    }
     public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelSetaPressionada = new javax.swing.JLabel();
        LabelEspaçoPressionada = new javax.swing.JLabel();
        LabelFarolPressionada = new javax.swing.JLabel();
        LabelBarPressionada = new javax.swing.JLabel();
        LabelAvaliação = new javax.swing.JLabel();
        BotaoHistoriaBar = new javax.swing.JButton();
        BotaoHistoriaFarol = new javax.swing.JButton();
        BotaoHistoriaEspaço = new javax.swing.JButton();
        BotaoSetaAvalicao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        LabelSetaPressionada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta avaliar historia pt1.png"))); // NOI18N
        LabelSetaPressionada.setText("jLabel1");
        LabelSetaPressionada.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        LabelSetaPressionada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelSetaPressionadaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelSetaPressionadaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LabelSetaPressionadaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LabelSetaPressionadaMouseReleased(evt);
            }
        });
        getContentPane().add(LabelSetaPressionada);
        LabelSetaPressionada.setBounds(0, 0, 1270, 720);

        LabelEspaçoPressionada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/espaco claro.png"))); // NOI18N
        LabelEspaçoPressionada.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(LabelEspaçoPressionada);
        LabelEspaçoPressionada.setBounds(0, 90, 1240, 530);

        LabelFarolPressionada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/farol claro.png"))); // NOI18N
        LabelFarolPressionada.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(LabelFarolPressionada);
        LabelFarolPressionada.setBounds(0, 60, 800, 590);

        LabelBarPressionada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bar claro.png"))); // NOI18N
        LabelBarPressionada.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(LabelBarPressionada);
        LabelBarPressionada.setBounds(0, 40, 460, 630);

        LabelAvaliação.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Tela-avaliação-pt.1.gif"))); // NOI18N
        getContentPane().add(LabelAvaliação);
        LabelAvaliação.setBounds(0, 0, 1270, 720);

        BotaoHistoriaBar.setText("jButton1");
        BotaoHistoriaBar.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BotaoHistoriaBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoHistoriaBarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoHistoriaBarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoHistoriaBarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoHistoriaBarMouseReleased(evt);
            }
        });
        BotaoHistoriaBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoHistoriaBarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoHistoriaBar);
        BotaoHistoriaBar.setBounds(130, 190, 260, 430);

        BotaoHistoriaFarol.setText("jButton1");
        BotaoHistoriaFarol.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BotaoHistoriaFarol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoHistoriaFarolMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoHistoriaFarolMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoHistoriaFarolMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoHistoriaFarolMouseReleased(evt);
            }
        });
        BotaoHistoriaFarol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoHistoriaFarolActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoHistoriaFarol);
        BotaoHistoriaFarol.setBounds(520, 190, 260, 430);

        BotaoHistoriaEspaço.setText("jButton1");
        BotaoHistoriaEspaço.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BotaoHistoriaEspaço.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoHistoriaEspaçoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoHistoriaEspaçoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoHistoriaEspaçoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoHistoriaEspaçoMouseReleased(evt);
            }
        });
        BotaoHistoriaEspaço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoHistoriaEspaçoActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoHistoriaEspaço);
        BotaoHistoriaEspaço.setBounds(900, 190, 250, 430);

        BotaoSetaAvalicao.setText("jButton1");
        BotaoSetaAvalicao.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BotaoSetaAvalicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoSetaAvalicaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoSetaAvalicaoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoSetaAvalicaoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoSetaAvalicaoMouseReleased(evt);
            }
        });
        BotaoSetaAvalicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSetaAvalicaoActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoSetaAvalicao);
        BotaoSetaAvalicao.setBounds(10, 650, 73, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoHistoriaEspaçoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoHistoriaEspaçoMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotaoHistoriaEspaçoMouseEntered

    private void BotaoHistoriaEspaçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoHistoriaEspaçoActionPerformed
        Avaliacao2 avaliacao2 = new Avaliacao2();
       avaliacao2.setUsuario(usuario);
       avaliacao2.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BotaoHistoriaEspaçoActionPerformed

    private void BotaoHistoriaEspaçoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoHistoriaEspaçoMouseExited
       Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoHistoriaEspaçoMouseExited

    private void BotaoHistoriaBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoHistoriaBarActionPerformed
       JOptionPane.showMessageDialog(this,"O Jogo não está concluido, por favor selicione outra história");
    }//GEN-LAST:event_BotaoHistoriaBarActionPerformed

    private void BotaoHistoriaBarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoHistoriaBarMouseEntered
         Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotaoHistoriaBarMouseEntered

    private void BotaoHistoriaBarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoHistoriaBarMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoHistoriaBarMouseExited

    private void BotaoHistoriaFarolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoHistoriaFarolActionPerformed
        Avaliacao2 avaliacao2 = new Avaliacao2();
       avaliacao2.setVisible(true);
       avaliacao2.setUsuario(usuario);
       avaliacao2.setCod(1);
       this.dispose();
    }//GEN-LAST:event_BotaoHistoriaFarolActionPerformed

    private void BotaoHistoriaFarolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoHistoriaFarolMouseEntered
         Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotaoHistoriaFarolMouseEntered

    private void BotaoHistoriaFarolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoHistoriaFarolMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoHistoriaFarolMouseExited

    private void BotaoSetaAvalicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSetaAvalicaoActionPerformed
        Perfil perfil = new Perfil ();
        perfil.setUsuario(usuario);
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoSetaAvalicaoActionPerformed

    private void BotaoSetaAvalicaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoSetaAvalicaoMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotaoSetaAvalicaoMouseEntered

    private void BotaoSetaAvalicaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoSetaAvalicaoMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoSetaAvalicaoMouseExited

    private void BotaoSetaAvalicaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoSetaAvalicaoMousePressed
        LabelSetaPressionada.setVisible(true);
        Perfil perfil = new Perfil ();
        perfil.setUsuario(usuario);
        perfil.setVisible(true);
        this.dispose();
        
        
    
    }//GEN-LAST:event_BotaoSetaAvalicaoMousePressed

    private void BotaoSetaAvalicaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoSetaAvalicaoMouseReleased
        LabelSetaPressionada.setVisible(false);
    }//GEN-LAST:event_BotaoSetaAvalicaoMouseReleased

    private void BotaoHistoriaBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoHistoriaBarMousePressed
        LabelBarPressionada.setVisible(true);
    }//GEN-LAST:event_BotaoHistoriaBarMousePressed

    private void BotaoHistoriaBarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoHistoriaBarMouseReleased
        LabelBarPressionada.setVisible(false);
    }//GEN-LAST:event_BotaoHistoriaBarMouseReleased

    private void BotaoHistoriaFarolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoHistoriaFarolMousePressed
       LabelFarolPressionada.setVisible(true);
    }//GEN-LAST:event_BotaoHistoriaFarolMousePressed

    private void BotaoHistoriaFarolMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoHistoriaFarolMouseReleased
        LabelFarolPressionada.setVisible(false);
    }//GEN-LAST:event_BotaoHistoriaFarolMouseReleased

    private void BotaoHistoriaEspaçoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoHistoriaEspaçoMousePressed
        LabelEspaçoPressionada.setVisible(true);
    }//GEN-LAST:event_BotaoHistoriaEspaçoMousePressed

    private void BotaoHistoriaEspaçoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoHistoriaEspaçoMouseReleased
        LabelEspaçoPressionada.setVisible(false);
    }//GEN-LAST:event_BotaoHistoriaEspaçoMouseReleased

    private void LabelSetaPressionadaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelSetaPressionadaMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_LabelSetaPressionadaMouseEntered

    private void LabelSetaPressionadaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelSetaPressionadaMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_LabelSetaPressionadaMouseExited

    private void LabelSetaPressionadaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelSetaPressionadaMousePressed
       LabelSetaPressionada.setVisible(true);
    }//GEN-LAST:event_LabelSetaPressionadaMousePressed

    private void LabelSetaPressionadaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelSetaPressionadaMouseReleased
        LabelSetaPressionada.setVisible(false);
    }//GEN-LAST:event_LabelSetaPressionadaMouseReleased
    
    
     
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoHistoriaBar;
    private javax.swing.JButton BotaoHistoriaEspaço;
    private javax.swing.JButton BotaoHistoriaFarol;
    private javax.swing.JButton BotaoSetaAvalicao;
    private javax.swing.JLabel LabelAvaliação;
    private javax.swing.JLabel LabelBarPressionada;
    private javax.swing.JLabel LabelEspaçoPressionada;
    private javax.swing.JLabel LabelFarolPressionada;
    private javax.swing.JLabel LabelSetaPressionada;
    // End of variables declaration//GEN-END:variables
}
