/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import java.awt.Cursor;
import javax.swing.JOptionPane;
import projeto.JogoDao;
import projeto.Usuario;

/**
 *
 * @author ewert
 */
public class Avaliacao2 extends javax.swing.JFrame {

    private Usuario usuario;
    private int cod;

    /**
     * Creates new form Avaliacao2
     */
    public Avaliacao2() {
        initComponents();
        this.setExtendedState(Avaliacao2.MAXIMIZED_BOTH);
        
        Label1EstrelaSelecionada.setVisible(false);
        Label2EstrelaSelecionada.setVisible(false);
        Label3EstrelaSelecionada.setVisible(false);
        Label4EstrelaSelecionada.setVisible(false);
        Label5EstrelaSelecionada.setVisible(false);
        LabelSetaPressionada.setVisible(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelSetaPressionada = new javax.swing.JLabel();
        Label5EstrelaSelecionada = new javax.swing.JLabel();
        Label4EstrelaSelecionada = new javax.swing.JLabel();
        Label3EstrelaSelecionada = new javax.swing.JLabel();
        Label2EstrelaSelecionada = new javax.swing.JLabel();
        Label1EstrelaSelecionada = new javax.swing.JLabel();
        LabelAvaliacao2 = new javax.swing.JLabel();
        BotaoEstrela1 = new javax.swing.JButton();
        BotaoEstrela2I = new javax.swing.JButton();
        BotaoEstrela2II = new javax.swing.JButton();
        BotaoEstrela3I = new javax.swing.JButton();
        BotaoEstrela3II = new javax.swing.JButton();
        BotaoEstrela3III = new javax.swing.JButton();
        BotaoEstrela4I = new javax.swing.JButton();
        BotaoEstrela4II = new javax.swing.JButton();
        BotaoEstrela4III = new javax.swing.JButton();
        BotaoEstrela4IV = new javax.swing.JButton();
        BotaoEstrela5I = new javax.swing.JButton();
        BotaoEstrela5II = new javax.swing.JButton();
        BotaoEstrela5III = new javax.swing.JButton();
        BotaoEstrela5IV = new javax.swing.JButton();
        BotaoEstrela5V = new javax.swing.JButton();
        BotaoReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        LabelSetaPressionada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta avaliacao pt2.png"))); // NOI18N
        LabelSetaPressionada.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(LabelSetaPressionada);
        LabelSetaPressionada.setBounds(0, 0, 1280, 720);

        Label5EstrelaSelecionada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/5 estrelitas.png"))); // NOI18N
        Label5EstrelaSelecionada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Label5EstrelaSelecionada);
        Label5EstrelaSelecionada.setBounds(0, 20, 1280, 720);

        Label4EstrelaSelecionada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/4 estrelas botao.png"))); // NOI18N
        Label4EstrelaSelecionada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Label4EstrelaSelecionada);
        Label4EstrelaSelecionada.setBounds(0, 0, 1280, 720);

        Label3EstrelaSelecionada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3 estrelas botao.png"))); // NOI18N
        Label3EstrelaSelecionada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Label3EstrelaSelecionada);
        Label3EstrelaSelecionada.setBounds(0, 0, 1280, 720);

        Label2EstrelaSelecionada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2 estrelas botao.png"))); // NOI18N
        Label2EstrelaSelecionada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Label2EstrelaSelecionada);
        Label2EstrelaSelecionada.setBounds(0, 0, 1280, 720);

        Label1EstrelaSelecionada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1 estrela botao.png"))); // NOI18N
        Label1EstrelaSelecionada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Label1EstrelaSelecionada);
        Label1EstrelaSelecionada.setBounds(0, 0, 1280, 720);

        LabelAvaliacao2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/avaliacao-pt2-fixxxx.gif"))); // NOI18N
        getContentPane().add(LabelAvaliacao2);
        LabelAvaliacao2.setBounds(0, 0, 1280, 720);

        BotaoEstrela1.setText("jButton1");
        BotaoEstrela1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoEstrela1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoEstrela1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoEstrela1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoEstrela1MouseReleased(evt);
            }
        });
        BotaoEstrela1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEstrela1ActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEstrela1);
        BotaoEstrela1.setBounds(323, 30, 90, 80);

        BotaoEstrela2I.setText("jButton2");
        BotaoEstrela2I.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoEstrela2IMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoEstrela2IMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoEstrela2IMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoEstrela2IMouseReleased(evt);
            }
        });
        BotaoEstrela2I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEstrela2IActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEstrela2I);
        BotaoEstrela2I.setBounds(320, 170, 90, 80);

        BotaoEstrela2II.setText("jButton3");
        BotaoEstrela2II.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoEstrela2IIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoEstrela2IIMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoEstrela2IIMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoEstrela2IIMouseReleased(evt);
            }
        });
        BotaoEstrela2II.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEstrela2IIActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEstrela2II);
        BotaoEstrela2II.setBounds(450, 170, 80, 80);

        BotaoEstrela3I.setText("jButton4");
        BotaoEstrela3I.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoEstrela3IMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoEstrela3IMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoEstrela3IMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoEstrela3IMouseReleased(evt);
            }
        });
        BotaoEstrela3I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEstrela3IActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEstrela3I);
        BotaoEstrela3I.setBounds(330, 310, 80, 80);

        BotaoEstrela3II.setText("jButton5");
        BotaoEstrela3II.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoEstrela3IIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoEstrela3IIMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoEstrela3IIMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoEstrela3IIMouseReleased(evt);
            }
        });
        BotaoEstrela3II.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEstrela3IIActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEstrela3II);
        BotaoEstrela3II.setBounds(453, 310, 80, 80);

        BotaoEstrela3III.setText("jButton6");
        BotaoEstrela3III.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoEstrela3IIIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoEstrela3IIIMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoEstrela3IIIMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoEstrela3IIIMouseReleased(evt);
            }
        });
        BotaoEstrela3III.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEstrela3IIIActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEstrela3III);
        BotaoEstrela3III.setBounds(570, 310, 80, 80);

        BotaoEstrela4I.setText("jButton7");
        BotaoEstrela4I.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoEstrela4IMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoEstrela4IMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoEstrela4IMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoEstrela4IMouseReleased(evt);
            }
        });
        BotaoEstrela4I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEstrela4IActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEstrela4I);
        BotaoEstrela4I.setBounds(320, 440, 90, 90);

        BotaoEstrela4II.setText("jButton8");
        BotaoEstrela4II.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoEstrela4IIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoEstrela4IIMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoEstrela4IIMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoEstrela4IIMouseReleased(evt);
            }
        });
        BotaoEstrela4II.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEstrela4IIActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEstrela4II);
        BotaoEstrela4II.setBounds(450, 440, 90, 90);

        BotaoEstrela4III.setText("jButton9");
        BotaoEstrela4III.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoEstrela4IIIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoEstrela4IIIMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoEstrela4IIIMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoEstrela4IIIMouseReleased(evt);
            }
        });
        BotaoEstrela4III.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEstrela4IIIActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEstrela4III);
        BotaoEstrela4III.setBounds(570, 440, 80, 90);

        BotaoEstrela4IV.setText("jButton10");
        BotaoEstrela4IV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoEstrela4IVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoEstrela4IVMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoEstrela4IVMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoEstrela4IVMouseReleased(evt);
            }
        });
        BotaoEstrela4IV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEstrela4IVActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEstrela4IV);
        BotaoEstrela4IV.setBounds(700, 440, 80, 90);

        BotaoEstrela5I.setText("jButton11");
        BotaoEstrela5I.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoEstrela5IMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoEstrela5IMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoEstrela5IMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoEstrela5IMouseReleased(evt);
            }
        });
        BotaoEstrela5I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEstrela5IActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEstrela5I);
        BotaoEstrela5I.setBounds(320, 580, 90, 80);

        BotaoEstrela5II.setText("jButton12");
        BotaoEstrela5II.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoEstrela5IIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoEstrela5IIMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoEstrela5IIMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoEstrela5IIMouseReleased(evt);
            }
        });
        BotaoEstrela5II.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEstrela5IIActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEstrela5II);
        BotaoEstrela5II.setBounds(440, 580, 90, 80);

        BotaoEstrela5III.setText("jButton13");
        BotaoEstrela5III.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoEstrela5IIIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoEstrela5IIIMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoEstrela5IIIMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoEstrela5IIIMouseReleased(evt);
            }
        });
        BotaoEstrela5III.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEstrela5IIIActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEstrela5III);
        BotaoEstrela5III.setBounds(570, 580, 90, 80);

        BotaoEstrela5IV.setText("jButton14");
        BotaoEstrela5IV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoEstrela5IVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoEstrela5IVMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoEstrela5IVMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoEstrela5IVMouseReleased(evt);
            }
        });
        BotaoEstrela5IV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEstrela5IVActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEstrela5IV);
        BotaoEstrela5IV.setBounds(690, 580, 90, 80);

        BotaoEstrela5V.setText("jButton15");
        BotaoEstrela5V.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoEstrela5VMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoEstrela5VMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoEstrela5VMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoEstrela5VMouseReleased(evt);
            }
        });
        BotaoEstrela5V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEstrela5VActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEstrela5V);
        BotaoEstrela5V.setBounds(809, 580, 80, 80);

        BotaoReturn.setText("jButton1");
        BotaoReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoReturnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoReturnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoReturnMouseReleased(evt);
            }
        });
        BotaoReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoReturnActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoReturn);
        BotaoReturn.setBounds(20, 640, 73, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setCod (int cod){
        this.cod = cod;
    }
    private void BotaoEstrela1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEstrela1ActionPerformed
        JogoDao jDao = new JogoDao();
        
        if ("farol".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            
            jDao.salvarAvaliacao(usuario,cod,1);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
           }
        if ("espaco".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,1);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
        if ("bar".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,1);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
        
    }//GEN-LAST:event_BotaoEstrela1ActionPerformed

    private void BotaoEstrela2IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEstrela2IActionPerformed
        JogoDao jDao = new JogoDao();
        
        if ("farol".equalsIgnoreCase(jDao.getNomeJogo(cod))){

            jDao.salvarAvaliacao(usuario,cod,2);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
           }
        if ("espaco".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,2);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
        if ("bar".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,2);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
    }//GEN-LAST:event_BotaoEstrela2IActionPerformed

    private void BotaoEstrela2IIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEstrela2IIActionPerformed
        JogoDao jDao = new JogoDao();
        int aux = 0;
        if ("farol".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            for (int i = 0; i< jDao.setNumeroEstrelas(usuario).size();i++){
                 if (jDao.getNumeroEstrelas(usuario).get(i) != 0){
                     
                     
                     JOptionPane.showMessageDialog(this, "Avaliacao atualizada com sucesso");
                     
                     aux ++;
                }  
            }
//            if (aux == 0){
//                jDao.salvarAvaliacao(usuario,cod,2);
//                JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
//            }
           }
        if ("espaco".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,2);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
        if ("bar".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,2);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
    }//GEN-LAST:event_BotaoEstrela2IIActionPerformed

    private void BotaoEstrela3IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEstrela3IActionPerformed
        JogoDao jDao = new JogoDao();
        
        if ("farol".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,3);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
           }
        if ("espaco".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,3);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
        if ("bar".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,3);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
        
    }//GEN-LAST:event_BotaoEstrela3IActionPerformed

    private void BotaoEstrela3IIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEstrela3IIActionPerformed
        JogoDao jDao = new JogoDao();
        
        if ("farol".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,3);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
           }
        if ("espaco".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,3);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
        if ("bar".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,3);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
    }//GEN-LAST:event_BotaoEstrela3IIActionPerformed

    private void BotaoEstrela3IIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEstrela3IIIActionPerformed
        JogoDao jDao = new JogoDao();
        
        if ("farol".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,3);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
           }
        if ("espaco".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,3);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
        if ("bar".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,3);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
    }//GEN-LAST:event_BotaoEstrela3IIIActionPerformed

    private void BotaoEstrela4IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEstrela4IActionPerformed
        JogoDao jDao = new JogoDao();
        
        if ("farol".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,4);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
           }
        if ("espaco".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,4);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
        if ("bar".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,4);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
    }//GEN-LAST:event_BotaoEstrela4IActionPerformed

    private void BotaoEstrela4IIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEstrela4IIActionPerformed
        JogoDao jDao = new JogoDao();
        
        if ("farol".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,4);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
           }
        if ("espaco".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,4);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
        if ("bar".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,4);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
    }//GEN-LAST:event_BotaoEstrela4IIActionPerformed

    private void BotaoEstrela4IIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEstrela4IIIActionPerformed
        JogoDao jDao = new JogoDao();
        
        if ("farol".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,4);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
           }
        if ("espaco".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,4);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
            
        }
        if ("bar".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,4);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
            
        }
    }//GEN-LAST:event_BotaoEstrela4IIIActionPerformed

    private void BotaoEstrela4IVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEstrela4IVActionPerformed
        JogoDao jDao = new JogoDao();
        
        if ("farol".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,4);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
           }
        if ("espaco".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,4);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
        if ("bar".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,4);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
    }//GEN-LAST:event_BotaoEstrela4IVActionPerformed

    private void BotaoEstrela5IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEstrela5IActionPerformed
        JogoDao jDao = new JogoDao();
        
        if ("farol".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,5);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
           }
        if ("espaco".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,5);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
        if ("bar".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,5);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
    }//GEN-LAST:event_BotaoEstrela5IActionPerformed

    private void BotaoEstrela5IIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEstrela5IIActionPerformed
        JogoDao jDao = new JogoDao();
        
        if ("farol".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            
            jDao.salvarAvaliacao(usuario,cod,5);
            
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
           }
        if ("espaco".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,5);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
        if ("bar".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            
            jDao.salvarAvaliacao(usuario,cod,5);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
    }//GEN-LAST:event_BotaoEstrela5IIActionPerformed

    private void BotaoEstrela5IIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEstrela5IIIActionPerformed
        JogoDao jDao = new JogoDao();
        
        if ("farol".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,5);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
           }
        if ("espaco".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,5);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
        if ("bar".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,5);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
    }//GEN-LAST:event_BotaoEstrela5IIIActionPerformed

    private void BotaoEstrela5IVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEstrela5IVActionPerformed
        JogoDao jDao = new JogoDao();
        
        if ("farol".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,5);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
           }
        if ("espaco".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,5);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
        if ("bar".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,5);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
    }//GEN-LAST:event_BotaoEstrela5IVActionPerformed

    private void BotaoEstrela5VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEstrela5VActionPerformed
        JogoDao jDao = new JogoDao();
        
        if ("farol".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,5);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
           }
        if ("espaco".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,5);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
        if ("bar".equalsIgnoreCase(jDao.getNomeJogo(cod))){
            jDao.salvarAvaliacao(usuario,cod,5);
            JOptionPane.showMessageDialog(this, "Avaliado com sucesso");
        }
    }//GEN-LAST:event_BotaoEstrela5VActionPerformed


//animações
    
    
    private void BotaoEstrela1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela1MouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
        Label1EstrelaSelecionada.setVisible(true);
        
    }//GEN-LAST:event_BotaoEstrela1MouseEntered

    private void BotaoEstrela1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela1MouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
        Label1EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela1MouseExited

    private void BotaoEstrela1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela1MousePressed
        Label1EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela1MousePressed

    private void BotaoEstrela1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela1MouseReleased
        Label1EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela1MouseReleased

    private void BotaoEstrela2IMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela2IMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
        Label2EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela2IMouseEntered

    private void BotaoEstrela2IMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela2IMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
        Label2EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela2IMouseExited

    private void BotaoEstrela2IMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela2IMousePressed
        Label2EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela2IMousePressed

    private void BotaoEstrela2IMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela2IMouseReleased
        Label2EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela2IMouseReleased

    private void BotaoEstrela2IIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela2IIMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
        Label2EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela2IIMouseEntered

    private void BotaoEstrela2IIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela2IIMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
        Label2EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela2IIMouseExited

    private void BotaoEstrela2IIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela2IIMousePressed
        Label2EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela2IIMousePressed

    private void BotaoEstrela2IIMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela2IIMouseReleased
        Label2EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela2IIMouseReleased

    private void BotaoEstrela3IMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela3IMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
        Label3EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela3IMouseEntered

    private void BotaoEstrela3IMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela3IMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
        Label3EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela3IMouseExited

    private void BotaoEstrela3IMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela3IMousePressed
        Label3EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela3IMousePressed

    private void BotaoEstrela3IMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela3IMouseReleased
        Label3EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela3IMouseReleased

    private void BotaoEstrela3IIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela3IIMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
        Label3EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela3IIMouseEntered

    private void BotaoEstrela3IIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela3IIMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
        Label3EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela3IIMouseExited

    private void BotaoEstrela3IIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela3IIMousePressed
        Label3EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela3IIMousePressed

    private void BotaoEstrela3IIMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela3IIMouseReleased
        Label3EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela3IIMouseReleased

    private void BotaoEstrela3IIIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela3IIIMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
        Label3EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela3IIIMouseEntered

    private void BotaoEstrela3IIIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela3IIIMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
        Label3EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela3IIIMouseExited

    private void BotaoEstrela3IIIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela3IIIMousePressed
        Label3EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela3IIIMousePressed

    private void BotaoEstrela3IIIMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela3IIIMouseReleased
        Label3EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela3IIIMouseReleased

    private void BotaoEstrela4IMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela4IMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
        Label4EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela4IMouseEntered

    private void BotaoEstrela4IMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela4IMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
        Label4EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela4IMouseExited

    private void BotaoEstrela4IMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela4IMousePressed
        Label4EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela4IMousePressed

    private void BotaoEstrela4IMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela4IMouseReleased
        Label4EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela4IMouseReleased

    private void BotaoEstrela4IIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela4IIMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
        Label4EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela4IIMouseEntered

    private void BotaoEstrela4IIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela4IIMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
        Label4EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela4IIMouseExited

    private void BotaoEstrela4IIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela4IIMousePressed
        Label4EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela4IIMousePressed

    private void BotaoEstrela4IIMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela4IIMouseReleased
        Label4EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela4IIMouseReleased

    private void BotaoEstrela4IIIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela4IIIMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
        Label4EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela4IIIMouseEntered

    private void BotaoEstrela4IIIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela4IIIMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
        Label4EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela4IIIMouseExited

    private void BotaoEstrela4IIIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela4IIIMousePressed
        Label4EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela4IIIMousePressed

    private void BotaoEstrela4IIIMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela4IIIMouseReleased
        Label4EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela4IIIMouseReleased

    private void BotaoEstrela4IVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela4IVMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
        Label4EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela4IVMouseEntered

    private void BotaoEstrela4IVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela4IVMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
        Label4EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela4IVMouseExited

    private void BotaoEstrela4IVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela4IVMousePressed
        Label4EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela4IVMousePressed

    private void BotaoEstrela4IVMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela4IVMouseReleased
        Label4EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela4IVMouseReleased

    private void BotaoEstrela5IMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela5IMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
        Label5EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela5IMouseEntered

    private void BotaoEstrela5IMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela5IMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
        Label5EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela5IMouseExited

    private void BotaoEstrela5IMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela5IMousePressed
        Label5EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela5IMousePressed

    private void BotaoEstrela5IMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela5IMouseReleased
        Label5EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela5IMouseReleased

    private void BotaoEstrela5IIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela5IIMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
        Label5EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela5IIMouseEntered

    private void BotaoEstrela5IIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela5IIMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
        Label5EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela5IIMouseExited

    private void BotaoEstrela5IIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela5IIMousePressed
        Label5EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela5IIMousePressed

    private void BotaoEstrela5IIMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela5IIMouseReleased
        Label5EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela5IIMouseReleased

    private void BotaoEstrela5IIIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela5IIIMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
        Label5EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela5IIIMouseEntered

    private void BotaoEstrela5IIIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela5IIIMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
        Label5EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela5IIIMouseExited

    private void BotaoEstrela5IIIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela5IIIMousePressed
        Label5EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela5IIIMousePressed

    private void BotaoEstrela5IIIMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela5IIIMouseReleased
        Label5EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela5IIIMouseReleased

    private void BotaoEstrela5IVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela5IVMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
        Label5EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela5IVMouseEntered

    private void BotaoEstrela5IVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela5IVMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
        Label5EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela5IVMouseExited

    private void BotaoEstrela5IVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela5IVMousePressed
        Label5EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela5IVMousePressed

    private void BotaoEstrela5IVMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela5IVMouseReleased
        Label5EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela5IVMouseReleased

    private void BotaoEstrela5VMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela5VMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
        Label5EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela5VMouseEntered

    private void BotaoEstrela5VMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela5VMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
        Label5EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela5VMouseExited

    private void BotaoEstrela5VMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela5VMousePressed
        Label5EstrelaSelecionada.setVisible(false);
    }//GEN-LAST:event_BotaoEstrela5VMousePressed

    private void BotaoEstrela5VMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstrela5VMouseReleased
        Label5EstrelaSelecionada.setVisible(true);
    }//GEN-LAST:event_BotaoEstrela5VMouseReleased

    private void BotaoReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoReturnActionPerformed
        Avaliacao1 avaliacao1 = new Avaliacao1 ();
        avaliacao1.setUsuario(usuario);
        avaliacao1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoReturnActionPerformed

    private void BotaoReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotaoReturnMouseEntered

    private void BotaoReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoReturnMouseExited

    private void BotaoReturnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMousePressed
        LabelSetaPressionada.setVisible(true);
    }//GEN-LAST:event_BotaoReturnMousePressed

    private void BotaoReturnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMouseReleased
        LabelSetaPressionada.setVisible(false);
    }//GEN-LAST:event_BotaoReturnMouseReleased

    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoEstrela1;
    private javax.swing.JButton BotaoEstrela2I;
    private javax.swing.JButton BotaoEstrela2II;
    private javax.swing.JButton BotaoEstrela3I;
    private javax.swing.JButton BotaoEstrela3II;
    private javax.swing.JButton BotaoEstrela3III;
    private javax.swing.JButton BotaoEstrela4I;
    private javax.swing.JButton BotaoEstrela4II;
    private javax.swing.JButton BotaoEstrela4III;
    private javax.swing.JButton BotaoEstrela4IV;
    private javax.swing.JButton BotaoEstrela5I;
    private javax.swing.JButton BotaoEstrela5II;
    private javax.swing.JButton BotaoEstrela5III;
    private javax.swing.JButton BotaoEstrela5IV;
    private javax.swing.JButton BotaoEstrela5V;
    private javax.swing.JButton BotaoReturn;
    private javax.swing.JLabel Label1EstrelaSelecionada;
    private javax.swing.JLabel Label2EstrelaSelecionada;
    private javax.swing.JLabel Label3EstrelaSelecionada;
    private javax.swing.JLabel Label4EstrelaSelecionada;
    private javax.swing.JLabel Label5EstrelaSelecionada;
    private javax.swing.JLabel LabelAvaliacao2;
    private javax.swing.JLabel LabelSetaPressionada;
    // End of variables declaration//GEN-END:variables

    void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
}
