/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;


import java.awt.Cursor;
import javax.swing.JOptionPane;
import musicas.Musica;
import projeto.ClasseArrylist;
import projeto.Usuario;




/**
 *
 * @author ewert
 */
public class Cadastro extends javax.swing.JFrame {

    private Object textfield;
    private Object color;
    private Object Color;

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        
        this.setExtendedState(Cadastro.MAXIMIZED_BOTH);
        
        LabelPressionado.setVisible(false);
        LabelSetaPressionada.setVisible(false);
//        Musica musica = new Musica();
//        musica.play("../musicas/musica_principal.wav");
       
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CaixaIdade = new javax.swing.JTextField();
        CaixaNome = new javax.swing.JTextField();
        CaixaGenero = new javax.swing.JTextField();
        CampoSenha1 = new javax.swing.JPasswordField();
        CampoSenha2 = new javax.swing.JPasswordField();
        LabelSetaPressionada = new javax.swing.JLabel();
        LabelPressionado = new javax.swing.JLabel();
        LabelCadastro = new javax.swing.JLabel();
        BotaoCadastro = new javax.swing.JButton();
        BotãoReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        CaixaIdade.setBackground(new java.awt.Color(255,255,255,0));
        CaixaIdade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        CaixaIdade.setOpaque(false);
        getContentPane().add(CaixaIdade);
        CaixaIdade.setBounds(580, 190, 70, 30);

        CaixaNome.setBackground(new java.awt.Color(255,255,255,0)
        );
        CaixaNome.setFont(new java.awt.Font("Charlemagne Std", 0, 11)); // NOI18N
        CaixaNome.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        CaixaNome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        CaixaNome.setCaretColor(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        CaixaNome.setOpaque(false);
        CaixaNome.setSelectedTextColor(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        getContentPane().add(CaixaNome);
        CaixaNome.setBounds(580, 150, 360, 30);

        CaixaGenero.setBackground(new java.awt.Color(255,255,255,0)
        );
        CaixaGenero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        CaixaGenero.setOpaque(false);
        getContentPane().add(CaixaGenero);
        CaixaGenero.setBounds(610, 230, 190, 20);

        CampoSenha1.setBackground(new java.awt.Color(255,255,255,0)
        );
        CampoSenha1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        CampoSenha1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        CampoSenha1.setOpaque(false);
        getContentPane().add(CampoSenha1);
        CampoSenha1.setBounds(590, 260, 360, 30);

        CampoSenha2.setBackground(new java.awt.Color(255,255,255,0)
        );
        CampoSenha2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        CampoSenha2.setOpaque(false);
        getContentPane().add(CampoSenha2);
        CampoSenha2.setBounds(600, 300, 350, 30);

        LabelSetaPressionada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/SetaCadastroPressionada.png"))); // NOI18N
        LabelSetaPressionada.setText("jLabel1");
        LabelSetaPressionada.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        LabelSetaPressionada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LabelSetaPressionadaMouseReleased(evt);
            }
        });
        getContentPane().add(LabelSetaPressionada);
        LabelSetaPressionada.setBounds(0, 0, 1280, 720);

        LabelPressionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pressionado.png"))); // NOI18N
        LabelPressionado.setText("jLabel1");
        LabelPressionado.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(LabelPressionado);
        LabelPressionado.setBounds(0, 0, 1280, 720);

        LabelCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Tela-de-cadastro.gif"))); // NOI18N
        LabelCadastro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(LabelCadastro);
        LabelCadastro.setBounds(0, 0, 1280, 720);

        BotaoCadastro.setText("jButton1");
        BotaoCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoCadastroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoCadastroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoCadastroMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoCadastroMouseReleased(evt);
            }
        });
        BotaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoCadastro);
        BotaoCadastro.setBounds(400, 590, 480, 110);

        BotãoReturn.setText("jButton1");
        BotãoReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotãoReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotãoReturnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotãoReturnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotãoReturnMouseReleased(evt);
            }
        });
        BotãoReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoReturnActionPerformed(evt);
            }
        });
        getContentPane().add(BotãoReturn);
        BotãoReturn.setBounds(0, 630, 100, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void BotãoReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoReturnActionPerformed
         Login login = new Login ();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotãoReturnActionPerformed

    private void BotãoReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotãoReturnMouseEntered
       Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotãoReturnMouseEntered

    private void BotãoReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotãoReturnMouseExited
       Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotãoReturnMouseExited

    private void BotaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroActionPerformed
        
        
        
        if (CampoSenha1.getText().equalsIgnoreCase("") ||  CaixaNome.getText().equalsIgnoreCase("") || CampoSenha2.getText().equalsIgnoreCase("") || CaixaGenero.getText().equalsIgnoreCase("") || CaixaIdade.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Preencha todo os campos de dados, por favor.");
       }
       else if (CampoSenha1.getText().equals(CampoSenha2.getText())) {
                Usuario usuario = new Usuario(0, CaixaNome.getText(),CampoSenha1.getText(),CaixaGenero.getText(),CaixaIdade.getText());
                ClasseArrylist CLA = new ClasseArrylist();
                CLA.adicionarUsuario(usuario);
                JOptionPane.showMessageDialog(this,"Cadastrado com sucesso");

       }
       else{
                JOptionPane.showMessageDialog(this,"Não é possivel cadastrar, verifique sua senha");
            }
       
    }//GEN-LAST:event_BotaoCadastroActionPerformed

    private void BotaoCadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoCadastroMouseEntered
       Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotaoCadastroMouseEntered

    private void BotaoCadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoCadastroMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoCadastroMouseExited

    private void BotaoCadastroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoCadastroMousePressed
        LabelPressionado.setVisible(true);
         
    }//GEN-LAST:event_BotaoCadastroMousePressed

    private void BotaoCadastroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoCadastroMouseReleased
        LabelPressionado.setVisible(false);
        
       
    }//GEN-LAST:event_BotaoCadastroMouseReleased

    private void LabelSetaPressionadaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelSetaPressionadaMouseReleased
        LabelSetaPressionada.setVisible(false);

    }//GEN-LAST:event_LabelSetaPressionadaMouseReleased

    private void BotãoReturnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotãoReturnMousePressed
        LabelSetaPressionada.setVisible(true);
        Login login = new Login ();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotãoReturnMousePressed

    private void BotãoReturnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotãoReturnMouseReleased
        LabelSetaPressionada.setVisible(false);
    }//GEN-LAST:event_BotãoReturnMouseReleased

    /**
     * @param args the command line arguments
     */
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastro;
    private javax.swing.JButton BotãoReturn;
    private javax.swing.JTextField CaixaGenero;
    private javax.swing.JTextField CaixaIdade;
    private javax.swing.JTextField CaixaNome;
    private javax.swing.JPasswordField CampoSenha1;
    private javax.swing.JPasswordField CampoSenha2;
    private javax.swing.JLabel LabelCadastro;
    private javax.swing.JLabel LabelPressionado;
    private javax.swing.JLabel LabelSetaPressionada;
    // End of variables declaration//GEN-END:variables
}
