/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import projeto.JogoDao;

/**
 *
 * @author ewert
 */
public class ExibirAvaliacoes extends javax.swing.JFrame {

    /**
     * Creates new form ExibirAvaliacoes
     */
    public ExibirAvaliacoes() {
        initComponents();
        JogoDao jDao = new JogoDao ();
        AvaliacaoShow.setText("\n");
        this.setExtendedState(ExibirAvaliacoes.MAXIMIZED_BOTH);
        for (int i = 0; i<jDao.getAvaliacoes().size();i++){
            AvaliacaoShow.setText(AvaliacaoShow.getText()+ jDao.getAvaliacoes());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelSeta = new javax.swing.JLabel();
        AvaliacaoShow = new javax.swing.JTextArea();
        LabelAvaliacao = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        LabelSeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/SetaCadastroPressionada.png"))); // NOI18N
        getContentPane().add(LabelSeta);
        LabelSeta.setBounds(1110, -600, 100, 690);

        AvaliacaoShow.setEditable(false);
        AvaliacaoShow.setBackground(new java.awt.Color(255,255,255,0)
        );
        AvaliacaoShow.setColumns(20);
        AvaliacaoShow.setFont(new java.awt.Font("Charlemagne Std", 0, 18)); // NOI18N
        AvaliacaoShow.setForeground(new java.awt.Color(255, 255, 255));
        AvaliacaoShow.setLineWrap(true);
        AvaliacaoShow.setRows(10);
        AvaliacaoShow.setTabSize(30);
        AvaliacaoShow.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AvaliacaoShow.setOpaque(false);
        getContentPane().add(AvaliacaoShow);
        AvaliacaoShow.setBounds(140, 190, 1000, 440);

        LabelAvaliacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela-feedback-avaliacoes.png"))); // NOI18N
        getContentPane().add(LabelAvaliacao);
        LabelAvaliacao.setBounds(0, 0, 1280, 720);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1120, 30, 73, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Mestre mestre = new Mestre ();
        mestre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AvaliacaoShow;
    private javax.swing.JLabel LabelAvaliacao;
    private javax.swing.JLabel LabelSeta;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
