/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Cursor;
import projeto.Usuario;

/**
 *
 * @author ewert
 */
public class FinalConcluido extends javax.swing.JFrame {

    private Usuario usuario;

    /**
     * Creates new form FinalConcluido
     */
    public FinalConcluido() {
        initComponents();
         this.setExtendedState(FinalConcluido.MAXIMIZED_BOTH);
        LabelBarPressionado.setVisible(false);
        LabelFarolPressionado.setVisible(false);
        LabelEspacoPressionado.setVisible(false);
        LabelSetaPressionado.setVisible(false);
        NumeroFinalConcluidoFarol.setText("0"+"metodo"+"/07");
        NumeroFinalConcluidoBar.setText("00"+"/07");
        NumeroFinalConcluidoEspaco.setText("00"+"/05");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NumeroFinalConcluidoEspaco = new javax.swing.JLabel();
        NumeroFinalConcluidoFarol = new javax.swing.JLabel();
        NumeroFinalConcluidoBar = new javax.swing.JLabel();
        LabelSetaPressionado = new javax.swing.JLabel();
        LabelEspacoPressionado = new javax.swing.JLabel();
        LabelFarolPressionado = new javax.swing.JLabel();
        LabelBarPressionado = new javax.swing.JLabel();
        LabelFinalConcluido = new javax.swing.JLabel();
        BotaoBar = new javax.swing.JButton();
        BotaoFarol = new javax.swing.JButton();
        BotaoEspaco = new javax.swing.JButton();
        BotaoReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        NumeroFinalConcluidoEspaco.setForeground(new java.awt.Color(255, 255, 255));
        NumeroFinalConcluidoEspaco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(NumeroFinalConcluidoEspaco);
        NumeroFinalConcluidoEspaco.setBounds(910, 540, 180, 50);

        NumeroFinalConcluidoFarol.setForeground(new java.awt.Color(255, 255, 255));
        NumeroFinalConcluidoFarol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(NumeroFinalConcluidoFarol);
        NumeroFinalConcluidoFarol.setBounds(560, 540, 170, 50);

        NumeroFinalConcluidoBar.setForeground(new java.awt.Color(255, 255, 255));
        NumeroFinalConcluidoBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(NumeroFinalConcluidoBar);
        NumeroFinalConcluidoBar.setBounds(220, 540, 170, 50);

        LabelSetaPressionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta finais concluidos.png"))); // NOI18N
        LabelSetaPressionado.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(LabelSetaPressionado);
        LabelSetaPressionado.setBounds(0, 0, 750, 720);

        LabelEspacoPressionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/espaco claro.png"))); // NOI18N
        LabelEspacoPressionado.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(LabelEspacoPressionado);
        LabelEspacoPressionado.setBounds(-30, 0, 1190, 520);

        LabelFarolPressionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/farol claro.png"))); // NOI18N
        LabelFarolPressionado.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(LabelFarolPressionado);
        LabelFarolPressionado.setBounds(0, -10, 800, 540);

        LabelBarPressionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bar claro.png"))); // NOI18N
        LabelBarPressionado.setText("jLabel1");
        LabelBarPressionado.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(LabelBarPressionado);
        LabelBarPressionado.setBounds(40, 0, 390, 520);

        LabelFinalConcluido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Tela-de-finais-concluidos.gif"))); // NOI18N
        getContentPane().add(LabelFinalConcluido);
        LabelFinalConcluido.setBounds(0, 0, 1280, 720);

        BotaoBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoBarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoBarMouseExited(evt);
            }
        });
        getContentPane().add(BotaoBar);
        BotaoBar.setBounds(170, 90, 260, 430);

        BotaoFarol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoFarolMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoFarolMouseExited(evt);
            }
        });
        getContentPane().add(BotaoFarol);
        BotaoFarol.setBounds(520, 90, 260, 430);

        BotaoEspaco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoEspacoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoEspacoMouseExited(evt);
            }
        });
        getContentPane().add(BotaoEspaco);
        BotaoEspaco.setBounds(870, 90, 260, 430);

        BotaoReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoReturnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoReturnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoReturnMouseReleased(evt);
            }
        });
        BotaoReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoReturnActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoReturn);
        BotaoReturn.setBounds(20, 640, 70, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoReturnActionPerformed
        Perfil perfil = new Perfil ();
        perfil.setUsuario(usuario);
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoReturnActionPerformed

    private void BotaoBarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBarMouseEntered
       Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotaoBarMouseEntered

    private void BotaoBarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBarMouseExited
       Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoBarMouseExited

    private void BotaoFarolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoFarolMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotaoFarolMouseEntered

    private void BotaoFarolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoFarolMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoFarolMouseExited

    private void BotaoEspacoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEspacoMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotaoEspacoMouseEntered

    private void BotaoEspacoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEspacoMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoEspacoMouseExited

    private void BotaoReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotaoReturnMouseEntered

    private void BotaoReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoReturnMouseExited

    private void BotaoReturnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMousePressed
        LabelSetaPressionado.setVisible(true);
    }//GEN-LAST:event_BotaoReturnMousePressed

    private void BotaoReturnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMouseReleased
        LabelSetaPressionado.setVisible(false);
    }//GEN-LAST:event_BotaoReturnMouseReleased

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoBar;
    private javax.swing.JButton BotaoEspaco;
    private javax.swing.JButton BotaoFarol;
    private javax.swing.JButton BotaoReturn;
    private javax.swing.JLabel LabelBarPressionado;
    private javax.swing.JLabel LabelEspacoPressionado;
    private javax.swing.JLabel LabelFarolPressionado;
    private javax.swing.JLabel LabelFinalConcluido;
    private javax.swing.JLabel LabelSetaPressionado;
    private javax.swing.JLabel NumeroFinalConcluidoBar;
    private javax.swing.JLabel NumeroFinalConcluidoEspaco;
    private javax.swing.JLabel NumeroFinalConcluidoFarol;
    // End of variables declaration//GEN-END:variables

    void setUsuario(Usuario usuario) {
       this.usuario = usuario;
    }
}
