/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Cursor;
import projeto.JogoDao;
import projeto.Usuario;

/**
 *
 * @author ewert
 */
public class Historico extends javax.swing.JFrame {

    private Usuario usuario;

    /**
     * Creates new form Historico
     */
    public Historico() {
        initComponents();
         this.setExtendedState(Historico.MAXIMIZED_BOTH);
        LabelSetaPressionada.setVisible(false);
        JogoDao jDao = new JogoDao();
        HistoricoShow.setText("\n"+"\n"+"\n");
        int x = jDao.getHistorico().size();
        
        for (int i = (x-1); i>=0;i--){
            HistoricoShow.setText(HistoricoShow.getText()+jDao.getHistorico().get(i)+"\n");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HistoricoShow = new javax.swing.JTextArea();
        LabelSetaPressionada = new javax.swing.JLabel();
        LabelHistorico = new javax.swing.JLabel();
        BotaoReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        HistoricoShow.setEditable(false);
        HistoricoShow.setBackground(new java.awt.Color(255,255,255,0)
        );
        HistoricoShow.setColumns(20);
        HistoricoShow.setFont(new java.awt.Font("Charlemagne Std", 0, 18)); // NOI18N
        HistoricoShow.setForeground(new java.awt.Color(255, 255, 255));
        HistoricoShow.setRows(5);
        HistoricoShow.setOpaque(false);
        getContentPane().add(HistoricoShow);
        HistoricoShow.setBounds(100, 210, 1110, 450);

        LabelSetaPressionada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta histórico.png"))); // NOI18N
        getContentPane().add(LabelSetaPressionada);
        LabelSetaPressionada.setBounds(0, 0, 1280, 720);

        LabelHistorico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Tela-de-histórico (1).gif"))); // NOI18N
        getContentPane().add(LabelHistorico);
        LabelHistorico.setBounds(0, 0, 1280, 720);

        BotaoReturn.setText("jButton1");
        BotaoReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoReturnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoReturnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoReturnMouseReleased(evt);
            }
        });
        BotaoReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoReturnActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoReturn);
        BotaoReturn.setBounds(1140, 0, 120, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoReturnActionPerformed
        Perfil perfil = new Perfil ();
        perfil.setUsuario(usuario);
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoReturnActionPerformed

    private void BotaoReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotaoReturnMouseEntered

    private void BotaoReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoReturnMouseExited

    private void BotaoReturnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMousePressed
        LabelSetaPressionada.setVisible(true);
    }//GEN-LAST:event_BotaoReturnMousePressed

    private void BotaoReturnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMouseReleased
        LabelSetaPressionada.setVisible(false);
    }//GEN-LAST:event_BotaoReturnMouseReleased

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoReturn;
    private javax.swing.JTextArea HistoricoShow;
    private javax.swing.JLabel LabelHistorico;
    private javax.swing.JLabel LabelSetaPressionada;
    // End of variables declaration//GEN-END:variables

    public void setUsuario(Usuario usuario) {
       this.usuario = usuario;
    }
}
