/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.event.KeyEvent;
import musicas.Musica;

/**
 *
 * @author ewert
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        
        initComponents();
        
        
        this.setExtendedState(Inicio.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelDeInicio = new javax.swing.JLabel();
        BotaoLabel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        getContentPane().setLayout(null);

        LabelDeInicio.setBackground(java.awt.SystemColor.activeCaptionText);
        LabelDeInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDeInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/main-screen-2.gif"))); // NOI18N
        LabelDeInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabelDeInicio.setMaximumSize(new java.awt.Dimension(1400, 720));
        LabelDeInicio.setPreferredSize(new java.awt.Dimension(1360, 720));
        LabelDeInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LabelDeInicioKeyPressed(evt);
            }
        });
        getContentPane().add(LabelDeInicio);
        LabelDeInicio.setBounds(0, 0, 1360, 720);

        BotaoLabel.setText("jButton1");
        BotaoLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLabelActionPerformed(evt);
            }
        });
        BotaoLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BotaoLabelKeyPressed(evt);
            }
        });
        getContentPane().add(BotaoLabel);
        BotaoLabel.setBounds(40, 0, 1280, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelDeInicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LabelDeInicioKeyPressed
        if(evt.getKeyCode() == KeyEvent.CHAR_UNDEFINED){
            Login login = new Login ();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_LabelDeInicioKeyPressed

    private void BotaoLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BotaoLabelKeyPressed
        int x = 0;
        x = evt.getKeyCode();
        if (x != 0){
             Login login = new Login ();
            
            login.setVisible(true);
            

            this.dispose();
        }
      

        
        
    }//GEN-LAST:event_BotaoLabelKeyPressed

    private void BotaoLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLabelActionPerformed
        Login login = new Login ();
            login.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_BotaoLabelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
                Musica musicas = new Musica ("../musicas/musga prinzipal.wav");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoLabel;
    private javax.swing.JLabel LabelDeInicio;
    // End of variables declaration//GEN-END:variables
}
