/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import projeto.JogoDao;
import projeto.Usuario;

/**
 *
 * @author ewert
 */
public class JogoEspaco extends javax.swing.JFrame {

    private Usuario usuario;

    /**
     * Creates new form JogoEspaco
     */
    public JogoEspaco() {
        initComponents();
        this.setExtendedState(JogoEspaco.MAXIMIZED_BOTH);
        
        LabelInicio1Paragrafo.setVisible(true);
        LabelInicio1Pergunta.setVisible(false);
        Label1NossosComputadores.setVisible(false);
        LabelEsperavaMais.setVisible(false);
        LabelOlaRecruta.setVisible(false);
        LabelDesistir.setVisible(false);
        LabelSeguirRotaOuNavegar.setVisible(false);
        LabelMudoudeIdeia.setVisible(false);
        LabelSeguirRota.setVisible(false);
        LabelNavegarContaPropria.setVisible(false);
        LabelPreBuraco.setVisible(false);
        LabelEntrandoNoBuraco.setVisible(false);
        LabelDecisaoDePlanetas.setVisible(false);
        LabelTentaculosEnormes.setVisible(false);
        LabelEntrarNoPlanetaLaranja.setVisible(false);
        LabelEntrandoPlanetaAzul.setVisible(false);
        LabelSaindoDaNave.setVisible(false);
        LabelCivilizacao.setVisible(false);
        LabelAbracos.setVisible(false);
        LabelumHomem.setVisible(false);
        LabelQualONome.setVisible(false);
        LabelProposta.setVisible(false);
        LabelAceitarOuRecusar.setVisible(false);
        LabelPreFim.setVisible(false);
        LabelFicarPlaneta.setVisible(false);
        LabelRecusarOferta.setVisible(false);
        LabelAjudaConsertar.setVisible(false);
        LabelCoordenadasOuPaz.setVisible(false);
        LabelCTE.setVisible(false);
        LabelMeChamoEdgar.setVisible(false);
        LabelFinalGenocidio.setVisible(false);
        LabelOphelia.setVisible(false);
        LabelFimSolitario.setVisible(false);
        
        
        BInicio1Pagrafo.setVisible(true);
        BSim1Pergunta.setVisible(false);
        BNossosComputadores.setVisible(false);
        BFimDesistir.setVisible(false);
        BNao1Pergunta.setVisible(false);
        BVoltarSelecaoHistoria.setVisible(false);
        BMudardeIdeia.setVisible(false);
        BNavegarPorContaPropria.setVisible(false);
        BSeguiraRota.setVisible(false);
        BRetornarHistoria.setVisible(false);
        BOlaRecruta.setVisible(false);
        BSeguirRota.setVisible(false);
        BNavegouSozinhoContaPropria.setVisible(false);
        BPreBuraco.setVisible(false);
        BEntrandoNoBuraco.setVisible(false);
        BDecisaoDePlanetasAzul.setVisible(false);
        BDecisaoDePlanetasLaranja.setVisible(false);
        BEntrarNoPlanetaLaranja.setVisible(false);
        BEntrandoPlanetaAzul.setVisible(false);
        BSaindoDaNave.setVisible(false);
        BCivilizacao.setVisible(false);
        BAbracos.setVisible(false);
        BumHomem.setVisible(false);
        BQualONome.setVisible(false);
        BProposta.setVisible(false);
        BAceitar.setVisible(false);
        BRecusar.setVisible(false);
        BPreFim.setVisible(false);
        BFinalFicarPlaneta.setVisible(false);
        BRecusarOferta.setVisible(false);
        BCoordenadas.setVisible(false);
        BDeixaremPaz.setVisible(false);
        BAjudaConsertar.setVisible(false);
        BCTE.setVisible(false);
        BFimSolitario.setVisible(false);
        BMeChamoEdgar.setVisible(false);
        BFinalGenocidio.setVisible(false);
        BFinalGenocidio.setVisible(false);
        BFimSolitario.setVisible(false);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelSaindoDaNave = new javax.swing.JLabel();
        LabelFicarPlaneta = new javax.swing.JLabel();
        LabelQualONome = new javax.swing.JLabel();
        LabelOphelia = new javax.swing.JLabel();
        LabelCoordenadasOuPaz = new javax.swing.JLabel();
        LabelAjudaConsertar = new javax.swing.JLabel();
        LabelRecusarOferta = new javax.swing.JLabel();
        LabelPreFim = new javax.swing.JLabel();
        LabelAceitarOuRecusar = new javax.swing.JLabel();
        LabelProposta = new javax.swing.JLabel();
        LabelumHomem = new javax.swing.JLabel();
        LabelAbracos = new javax.swing.JLabel();
        LabelCivilizacao = new javax.swing.JLabel();
        LabelEntrandoPlanetaAzul = new javax.swing.JLabel();
        LabelEntrarNoPlanetaLaranja = new javax.swing.JLabel();
        LabelTentaculosEnormes = new javax.swing.JLabel();
        LabelDecisaoDePlanetas = new javax.swing.JLabel();
        LabelEntrandoNoBuraco = new javax.swing.JLabel();
        LabelPreBuraco = new javax.swing.JLabel();
        LabelSeguirRota = new javax.swing.JLabel();
        LabelNavegarContaPropria = new javax.swing.JLabel();
        LabelMudoudeIdeia = new javax.swing.JLabel();
        LabelSeguirRotaOuNavegar = new javax.swing.JLabel();
        LabelDesistir = new javax.swing.JLabel();
        LabelEsperavaMais = new javax.swing.JLabel();
        LabelInicio1Pergunta = new javax.swing.JLabel();
        LabelOlaRecruta = new javax.swing.JLabel();
        LabelInicio1Paragrafo = new javax.swing.JLabel();
        Label1NossosComputadores = new javax.swing.JLabel();
        BAceitar = new javax.swing.JButton();
        BRecusar = new javax.swing.JButton();
        BAbracos = new javax.swing.JButton();
        BSaindoDaNave = new javax.swing.JButton();
        BEntrandoPlanetaAzul = new javax.swing.JButton();
        BDecisaoDePlanetasLaranja = new javax.swing.JButton();
        BDecisaoDePlanetasAzul = new javax.swing.JButton();
        BNavegarPorContaPropria = new javax.swing.JButton();
        BSeguiraRota = new javax.swing.JButton();
        BVoltarSelecaoHistoria = new javax.swing.JButton();
        BMudardeIdeia = new javax.swing.JButton();
        BNao1Pergunta = new javax.swing.JButton();
        BSim1Pergunta = new javax.swing.JButton();
        BInicio1Pagrafo = new javax.swing.JButton();
        BNossosComputadores = new javax.swing.JButton();
        BFimDesistir = new javax.swing.JButton();
        BRetornarHistoria = new javax.swing.JButton();
        BOlaRecruta = new javax.swing.JButton();
        BSeguirRota = new javax.swing.JButton();
        BNavegouSozinhoContaPropria = new javax.swing.JButton();
        BPreBuraco = new javax.swing.JButton();
        BEntrandoNoBuraco = new javax.swing.JButton();
        BTentaculosEnome = new javax.swing.JButton();
        BEntrarNoPlanetaLaranja = new javax.swing.JButton();
        BCivilizacao = new javax.swing.JButton();
        BumHomem = new javax.swing.JButton();
        BQualONome = new javax.swing.JButton();
        BCoordenadas = new javax.swing.JButton();
        BDeixaremPaz = new javax.swing.JButton();
        BProposta = new javax.swing.JButton();
        BPreFim = new javax.swing.JButton();
        BFinalFicarPlaneta = new javax.swing.JButton();
        BRecusarOferta = new javax.swing.JButton();
        BAjudaConsertar = new javax.swing.JButton();
        LabelCTE = new javax.swing.JLabel();
        LabelMeChamoEdgar = new javax.swing.JLabel();
        LabelFinalGenocidio = new javax.swing.JLabel();
        LabelFimSolitario = new javax.swing.JLabel();
        BCTE = new javax.swing.JButton();
        BMeChamoEdgar = new javax.swing.JButton();
        BFinalGenocidio = new javax.swing.JButton();
        BOphelia = new javax.swing.JButton();
        BFimSolitario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        LabelSaindoDaNave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/12.Saindo-da-nave.gif"))); // NOI18N
        LabelSaindoDaNave.setText("jLabel1");
        getContentPane().add(LabelSaindoDaNave);
        LabelSaindoDaNave.setBounds(0, 0, 1250, 720);

        LabelFicarPlaneta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/20.FINAL-FICAR-NO-PLANETA.gif"))); // NOI18N
        LabelFicarPlaneta.setText("jLabel1");
        getContentPane().add(LabelFicarPlaneta);
        LabelFicarPlaneta.setBounds(0, -50, 1810, 830);

        LabelQualONome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/16.Qual-seu-nome.gif"))); // NOI18N
        LabelQualONome.setText("jLabel2");
        getContentPane().add(LabelQualONome);
        LabelQualONome.setBounds(-30, -80, 1610, 880);

        LabelOphelia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/27.Ophelia.gif"))); // NOI18N
        LabelOphelia.setText("jLabel4");
        getContentPane().add(LabelOphelia);
        LabelOphelia.setBounds(0, -190, 2090, 1100);

        LabelCoordenadasOuPaz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/23.Coordenadas-ou-deixar-em-paz.gif"))); // NOI18N
        LabelCoordenadasOuPaz.setText("jLabel1");
        getContentPane().add(LabelCoordenadasOuPaz);
        LabelCoordenadasOuPaz.setBounds(0, 0, 1260, 740);

        LabelAjudaConsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/22.Me-ajuda-a-consertar.gif"))); // NOI18N
        LabelAjudaConsertar.setText("jLabel3");
        getContentPane().add(LabelAjudaConsertar);
        LabelAjudaConsertar.setBounds(0, 0, 1318, 720);

        LabelRecusarOferta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/21.Recusar-oferta.gif"))); // NOI18N
        getContentPane().add(LabelRecusarOferta);
        LabelRecusarOferta.setBounds(0, -30, 1400, 780);

        LabelPreFim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/19.Pre-fim.gif"))); // NOI18N
        getContentPane().add(LabelPreFim);
        LabelPreFim.setBounds(0, 0, 1250, 720);

        LabelAceitarOuRecusar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/18.Aceitar-ou-recusar.gif"))); // NOI18N
        getContentPane().add(LabelAceitarOuRecusar);
        LabelAceitarOuRecusar.setBounds(0, 0, 1250, 720);

        LabelProposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/17.Proposta.gif"))); // NOI18N
        LabelProposta.setText("jLabel3");
        getContentPane().add(LabelProposta);
        LabelProposta.setBounds(0, 0, 1250, 720);

        LabelumHomem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/15.Um-homem.gif"))); // NOI18N
        LabelumHomem.setText("jLabel1");
        getContentPane().add(LabelumHomem);
        LabelumHomem.setBounds(0, 0, 1318, 720);

        LabelAbracos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/14.Abraços.gif"))); // NOI18N
        LabelAbracos.setText("jLabel1");
        getContentPane().add(LabelAbracos);
        LabelAbracos.setBounds(0, 0, 1250, 720);

        LabelCivilizacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/13.Civilização.gif"))); // NOI18N
        getContentPane().add(LabelCivilizacao);
        LabelCivilizacao.setBounds(-6, 0, 1250, 720);

        LabelEntrandoPlanetaAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/11.Entrar-planeta-azul.gif"))); // NOI18N
        LabelEntrandoPlanetaAzul.setText("jLabel1");
        getContentPane().add(LabelEntrandoPlanetaAzul);
        LabelEntrandoPlanetaAzul.setBounds(0, 0, 1250, 720);

        LabelEntrarNoPlanetaLaranja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/9.Entrar-planeta-laranja.gif"))); // NOI18N
        LabelEntrarNoPlanetaLaranja.setText("jLabel1");
        getContentPane().add(LabelEntrarNoPlanetaLaranja);
        LabelEntrarNoPlanetaLaranja.setBounds(0, 4, 1318, 720);

        LabelTentaculosEnormes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/10.Tentaculos-enormes.gif"))); // NOI18N
        getContentPane().add(LabelTentaculosEnormes);
        LabelTentaculosEnormes.setBounds(0, 0, 1250, 720);

        LabelDecisaoDePlanetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/8.Pousar-planeta.gif"))); // NOI18N
        LabelDecisaoDePlanetas.setText("jLabel1");
        getContentPane().add(LabelDecisaoDePlanetas);
        LabelDecisaoDePlanetas.setBounds(0, 0, 1250, 720);

        LabelEntrandoNoBuraco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/7.Entrando-no-buraco.gif"))); // NOI18N
        getContentPane().add(LabelEntrandoNoBuraco);
        LabelEntrandoNoBuraco.setBounds(0, 0, 1250, 720);

        LabelPreBuraco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/6.Pré-buraco.gif"))); // NOI18N
        getContentPane().add(LabelPreBuraco);
        LabelPreBuraco.setBounds(0, 0, 1250, 720);

        LabelSeguirRota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/4.Seguir-rota.gif"))); // NOI18N
        getContentPane().add(LabelSeguirRota);
        LabelSeguirRota.setBounds(0, 0, 1250, 720);

        LabelNavegarContaPropria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/5.Navegar-por-conta-própria.gif"))); // NOI18N
        LabelNavegarContaPropria.setText("jLabel1");
        getContentPane().add(LabelNavegarContaPropria);
        LabelNavegarContaPropria.setBounds(0, 0, 1250, 720);

        LabelMudoudeIdeia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/x2.Mudou-de-ideia.gif"))); // NOI18N
        getContentPane().add(LabelMudoudeIdeia);
        LabelMudoudeIdeia.setBounds(0, 0, 1250, 720);

        LabelSeguirRotaOuNavegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/3.Seguir-rota-ou-navegar.gif"))); // NOI18N
        getContentPane().add(LabelSeguirRotaOuNavegar);
        LabelSeguirRotaOuNavegar.setBounds(0, 0, 1250, 720);

        LabelDesistir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/xxFIM-DESISTIR-VIAGEM_1.gif"))); // NOI18N
        getContentPane().add(LabelDesistir);
        LabelDesistir.setBounds(0, 0, 1250, 720);

        LabelEsperavaMais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/x1.Esperava-mais.gif"))); // NOI18N
        getContentPane().add(LabelEsperavaMais);
        LabelEsperavaMais.setBounds(0, 0, 1250, 720);

        LabelInicio1Pergunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/inicio-1°-pergunta.gif"))); // NOI18N
        LabelInicio1Pergunta.setText("jLabel1");
        getContentPane().add(LabelInicio1Pergunta);
        LabelInicio1Pergunta.setBounds(0, 0, 1250, 720);

        LabelOlaRecruta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/2.Olá-recruta.gif"))); // NOI18N
        LabelOlaRecruta.setText("jLabel1");
        getContentPane().add(LabelOlaRecruta);
        LabelOlaRecruta.setBounds(-6, 0, 1250, 720);

        LabelInicio1Paragrafo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/inicio-1°Paragrafo.gif"))); // NOI18N
        getContentPane().add(LabelInicio1Paragrafo);
        LabelInicio1Paragrafo.setBounds(0, 0, 1250, 720);

        Label1NossosComputadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/1.Nossos-computadores.gif"))); // NOI18N
        getContentPane().add(Label1NossosComputadores);
        Label1NossosComputadores.setBounds(0, 0, 1250, 720);

        BAceitar.setText("jButton1");
        BAceitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAceitarActionPerformed(evt);
            }
        });
        getContentPane().add(BAceitar);
        BAceitar.setBounds(180, 600, 350, 90);

        BRecusar.setText("jButton2");
        BRecusar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRecusarActionPerformed(evt);
            }
        });
        getContentPane().add(BRecusar);
        BRecusar.setBounds(730, 600, 370, 90);

        BAbracos.setText("jButton1");
        BAbracos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAbracosActionPerformed(evt);
            }
        });
        getContentPane().add(BAbracos);
        BAbracos.setBounds(0, 0, 1250, 720);

        BSaindoDaNave.setText("jButton1");
        BSaindoDaNave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSaindoDaNaveActionPerformed(evt);
            }
        });
        getContentPane().add(BSaindoDaNave);
        BSaindoDaNave.setBounds(0, 0, 1250, 720);

        BEntrandoPlanetaAzul.setText("jButton1");
        BEntrandoPlanetaAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEntrandoPlanetaAzulActionPerformed(evt);
            }
        });
        getContentPane().add(BEntrandoPlanetaAzul);
        BEntrandoPlanetaAzul.setBounds(0, 0, 1250, 720);

        BDecisaoDePlanetasLaranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDecisaoDePlanetasLaranjaActionPerformed(evt);
            }
        });
        getContentPane().add(BDecisaoDePlanetasLaranja);
        BDecisaoDePlanetasLaranja.setBounds(683, 450, 430, 190);

        BDecisaoDePlanetasAzul.setText("jButton1");
        BDecisaoDePlanetasAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDecisaoDePlanetasAzulActionPerformed(evt);
            }
        });
        getContentPane().add(BDecisaoDePlanetasAzul);
        BDecisaoDePlanetasAzul.setBounds(80, 450, 490, 200);

        BNavegarPorContaPropria.setText("jButton2");
        BNavegarPorContaPropria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNavegarPorContaPropriaActionPerformed(evt);
            }
        });
        getContentPane().add(BNavegarPorContaPropria);
        BNavegarPorContaPropria.setBounds(750, 280, 480, 240);

        BSeguiraRota.setText("jButton1");
        BSeguiraRota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSeguiraRotaActionPerformed(evt);
            }
        });
        getContentPane().add(BSeguiraRota);
        BSeguiraRota.setBounds(130, 330, 360, 190);

        BVoltarSelecaoHistoria.setText("jButton1");
        BVoltarSelecaoHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVoltarSelecaoHistoriaActionPerformed(evt);
            }
        });
        getContentPane().add(BVoltarSelecaoHistoria);
        BVoltarSelecaoHistoria.setBounds(1070, 610, 180, 110);

        BMudardeIdeia.setText("jButton1");
        BMudardeIdeia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMudardeIdeiaActionPerformed(evt);
            }
        });
        getContentPane().add(BMudardeIdeia);
        BMudardeIdeia.setBounds(130, 500, 400, 150);

        BNao1Pergunta.setText("jButton1");
        BNao1Pergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNao1PerguntaActionPerformed(evt);
            }
        });
        getContentPane().add(BNao1Pergunta);
        BNao1Pergunta.setBounds(700, 590, 280, 100);

        BSim1Pergunta.setText("jButton1");
        BSim1Pergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSim1PerguntaActionPerformed(evt);
            }
        });
        getContentPane().add(BSim1Pergunta);
        BSim1Pergunta.setBounds(290, 590, 290, 100);

        BInicio1Pagrafo.setText("jButton1");
        BInicio1Pagrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInicio1PagrafoActionPerformed(evt);
            }
        });
        getContentPane().add(BInicio1Pagrafo);
        BInicio1Pagrafo.setBounds(0, 180, 1250, 540);

        BNossosComputadores.setText("jButton1");
        BNossosComputadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNossosComputadoresActionPerformed(evt);
            }
        });
        getContentPane().add(BNossosComputadores);
        BNossosComputadores.setBounds(0, 0, 1250, 720);

        BFimDesistir.setText("jButton1");
        BFimDesistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFimDesistirActionPerformed(evt);
            }
        });
        getContentPane().add(BFimDesistir);
        BFimDesistir.setBounds(760, 510, 370, 150);

        BRetornarHistoria.setText("jButton1");
        BRetornarHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRetornarHistoriaActionPerformed(evt);
            }
        });
        getContentPane().add(BRetornarHistoria);
        BRetornarHistoria.setBounds(160, 180, 1090, 540);

        BOlaRecruta.setText("jButton1");
        BOlaRecruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOlaRecrutaActionPerformed(evt);
            }
        });
        getContentPane().add(BOlaRecruta);
        BOlaRecruta.setBounds(0, 0, 1250, 720);

        BSeguirRota.setText("jButton1");
        BSeguirRota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSeguirRotaActionPerformed(evt);
            }
        });
        getContentPane().add(BSeguirRota);
        BSeguirRota.setBounds(3, 3, 1250, 720);

        BNavegouSozinhoContaPropria.setText("jButton1");
        BNavegouSozinhoContaPropria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNavegouSozinhoContaPropriaActionPerformed(evt);
            }
        });
        getContentPane().add(BNavegouSozinhoContaPropria);
        BNavegouSozinhoContaPropria.setBounds(3, 3, 1240, 720);

        BPreBuraco.setText("jButton1");
        BPreBuraco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPreBuracoActionPerformed(evt);
            }
        });
        getContentPane().add(BPreBuraco);
        BPreBuraco.setBounds(0, 0, 1250, 720);

        BEntrandoNoBuraco.setText("jButton1");
        BEntrandoNoBuraco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEntrandoNoBuracoActionPerformed(evt);
            }
        });
        getContentPane().add(BEntrandoNoBuraco);
        BEntrandoNoBuraco.setBounds(0, 0, 1250, 720);

        BTentaculosEnome.setText("jButton1");
        BTentaculosEnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTentaculosEnomeActionPerformed(evt);
            }
        });
        getContentPane().add(BTentaculosEnome);
        BTentaculosEnome.setBounds(0, 0, 1250, 720);

        BEntrarNoPlanetaLaranja.setText("jButton1");
        BEntrarNoPlanetaLaranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEntrarNoPlanetaLaranjaActionPerformed(evt);
            }
        });
        getContentPane().add(BEntrarNoPlanetaLaranja);
        BEntrarNoPlanetaLaranja.setBounds(0, 0, 1250, 730);

        BCivilizacao.setText("jButton1");
        BCivilizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCivilizacaoActionPerformed(evt);
            }
        });
        getContentPane().add(BCivilizacao);
        BCivilizacao.setBounds(0, 0, 1250, 720);

        BumHomem.setText("jButton1");
        BumHomem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BumHomemActionPerformed(evt);
            }
        });
        getContentPane().add(BumHomem);
        BumHomem.setBounds(0, 0, 1250, 720);

        BQualONome.setText("jButton1");
        BQualONome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BQualONomeActionPerformed(evt);
            }
        });
        getContentPane().add(BQualONome);
        BQualONome.setBounds(0, 0, 1250, 720);

        BCoordenadas.setText("jButton1");
        BCoordenadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCoordenadasActionPerformed(evt);
            }
        });
        getContentPane().add(BCoordenadas);
        BCoordenadas.setBounds(60, 460, 530, 190);

        BDeixaremPaz.setText("jButton1");
        BDeixaremPaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDeixaremPazActionPerformed(evt);
            }
        });
        getContentPane().add(BDeixaremPaz);
        BDeixaremPaz.setBounds(780, 460, 410, 190);

        BProposta.setText("jButton1");
        BProposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPropostaActionPerformed(evt);
            }
        });
        getContentPane().add(BProposta);
        BProposta.setBounds(0, 0, 1250, 720);

        BPreFim.setText("jButton1");
        BPreFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPreFimActionPerformed(evt);
            }
        });
        getContentPane().add(BPreFim);
        BPreFim.setBounds(0, 0, 1250, 720);

        BFinalFicarPlaneta.setText("jButton1");
        BFinalFicarPlaneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFinalFicarPlanetaActionPerformed(evt);
            }
        });
        getContentPane().add(BFinalFicarPlaneta);
        BFinalFicarPlaneta.setBounds(1033, 573, 210, 140);

        BRecusarOferta.setText("jButton2");
        BRecusarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRecusarOfertaActionPerformed(evt);
            }
        });
        getContentPane().add(BRecusarOferta);
        BRecusarOferta.setBounds(0, 0, 1250, 720);

        BAjudaConsertar.setText("jButton3");
        BAjudaConsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAjudaConsertarActionPerformed(evt);
            }
        });
        getContentPane().add(BAjudaConsertar);
        BAjudaConsertar.setBounds(3, 3, 1240, 720);

        LabelCTE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/24.C.E.T.gif"))); // NOI18N
        LabelCTE.setText("jLabel1");
        getContentPane().add(LabelCTE);
        LabelCTE.setBounds(4, 0, 1240, 720);

        LabelMeChamoEdgar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/25.Me-chamo-Edgar.gif"))); // NOI18N
        LabelMeChamoEdgar.setText("jLabel2");
        getContentPane().add(LabelMeChamoEdgar);
        LabelMeChamoEdgar.setBounds(4, 0, 1240, 720);

        LabelFinalGenocidio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/26.FINAL-GENOCIDIO.gif"))); // NOI18N
        LabelFinalGenocidio.setText("jLabel3");
        getContentPane().add(LabelFinalGenocidio);
        LabelFinalGenocidio.setBounds(4, 4, 1240, 720);

        LabelFimSolitario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaco/28.FIM-SOLITARIO.gif"))); // NOI18N
        LabelFimSolitario.setText("jLabel1");
        getContentPane().add(LabelFimSolitario);
        LabelFimSolitario.setBounds(-2, 0, 2140, 950);

        BCTE.setText("jButton1");
        getContentPane().add(BCTE);
        BCTE.setBounds(3, 3, 1240, 720);

        BMeChamoEdgar.setText("jButton2");
        BMeChamoEdgar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMeChamoEdgarActionPerformed(evt);
            }
        });
        getContentPane().add(BMeChamoEdgar);
        BMeChamoEdgar.setBounds(3, 3, 1240, 710);

        BFinalGenocidio.setText("jButton3");
        BFinalGenocidio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFinalGenocidioActionPerformed(evt);
            }
        });
        getContentPane().add(BFinalGenocidio);
        BFinalGenocidio.setBounds(990, 580, 260, 140);

        BOphelia.setText("jButton4");
        BOphelia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOpheliaActionPerformed(evt);
            }
        });
        getContentPane().add(BOphelia);
        BOphelia.setBounds(3, 3, 1240, 720);

        BFimSolitario.setText("jButton1");
        BFimSolitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFimSolitarioActionPerformed(evt);
            }
        });
        getContentPane().add(BFimSolitario);
        BFimSolitario.setBounds(940, 560, 310, 160);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BInicio1PagrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInicio1PagrafoActionPerformed
        LabelInicio1Paragrafo.setVisible(false);
        BInicio1Pagrafo.setVisible(false);
        LabelInicio1Pergunta.setVisible(true);
        BSim1Pergunta.setVisible(true);
        BNao1Pergunta.setVisible(true);
    }//GEN-LAST:event_BInicio1PagrafoActionPerformed

    private void BSim1PerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSim1PerguntaActionPerformed
        LabelInicio1Pergunta.setVisible(false);
        BSim1Pergunta.setVisible(false);
        BNao1Pergunta.setVisible(false);
        Label1NossosComputadores.setVisible(true);
        BNossosComputadores.setVisible(true);
        
        
    }//GEN-LAST:event_BSim1PerguntaActionPerformed

    private void BNossosComputadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNossosComputadoresActionPerformed
        Label1NossosComputadores.setVisible(false);
        BNossosComputadores.setVisible(false);
        LabelOlaRecruta.setVisible(true);
        BOlaRecruta.setVisible(true);
        
        
    }//GEN-LAST:event_BNossosComputadoresActionPerformed

    private void BNao1PerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNao1PerguntaActionPerformed
        BNao1Pergunta.setVisible(false);
        LabelInicio1Pergunta.setVisible(false);
        BSim1Pergunta.setVisible(false);
        LabelEsperavaMais.setVisible(true);
        BMudardeIdeia.setVisible(true);
        BFimDesistir.setVisible(true);
        
    }//GEN-LAST:event_BNao1PerguntaActionPerformed

    private void BVoltarSelecaoHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVoltarSelecaoHistoriaActionPerformed
        BFimDesistir.setVisible(false);
        BVoltarSelecaoHistoria.setVisible(true);
        SelecaoHistoria selecaoHistoria = new SelecaoHistoria();
        JogoDao jDao = new JogoDao ();
        jDao.salvarHistorico(usuario, 8);
        selecaoHistoria.setUsuario(usuario);
        selecaoHistoria.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BVoltarSelecaoHistoriaActionPerformed

    private void BFimDesistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFimDesistirActionPerformed
        LabelEsperavaMais.setVisible(false);
        
        BMudardeIdeia.setVisible(false);
        BFimDesistir.setVisible(false);
        LabelDesistir.setVisible(true);
        BVoltarSelecaoHistoria.setVisible(true);
    }//GEN-LAST:event_BFimDesistirActionPerformed

    private void BMudardeIdeiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMudardeIdeiaActionPerformed
        LabelEsperavaMais.setVisible(false);
        BMudardeIdeia.setVisible(false);
        BFimDesistir.setVisible(false);
        LabelMudoudeIdeia.setVisible(true);
        BRetornarHistoria.setVisible(true);
        
    }//GEN-LAST:event_BMudardeIdeiaActionPerformed

    private void BRetornarHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRetornarHistoriaActionPerformed
        LabelMudoudeIdeia.setVisible(false);
        BRetornarHistoria.setVisible(false);
        Label1NossosComputadores.setVisible(true);
        BNossosComputadores.setVisible(true);
    }//GEN-LAST:event_BRetornarHistoriaActionPerformed

    private void BOlaRecrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOlaRecrutaActionPerformed
        LabelOlaRecruta.setVisible(false);
        BOlaRecruta.setVisible(false);
        LabelSeguirRotaOuNavegar.setVisible(true);
        BNavegarPorContaPropria.setVisible(true);
        BSeguiraRota.setVisible(true);
    }//GEN-LAST:event_BOlaRecrutaActionPerformed

    private void BSeguiraRotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSeguiraRotaActionPerformed
        LabelSeguirRotaOuNavegar.setVisible(false);
        BNavegarPorContaPropria.setVisible(false);
        BSeguiraRota.setVisible(false);
        LabelSeguirRota.setVisible(true);
        BSeguirRota.setVisible(true);
        
        
    }//GEN-LAST:event_BSeguiraRotaActionPerformed

    private void BNavegarPorContaPropriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNavegarPorContaPropriaActionPerformed
        LabelSeguirRotaOuNavegar.setVisible(false);
        BNavegarPorContaPropria.setVisible(false);
        BSeguiraRota.setVisible(false);
        LabelNavegarContaPropria.setVisible(true);
        BNavegouSozinhoContaPropria.setVisible(true);
    }//GEN-LAST:event_BNavegarPorContaPropriaActionPerformed

    private void BNavegouSozinhoContaPropriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNavegouSozinhoContaPropriaActionPerformed
        LabelNavegarContaPropria.setVisible(false);
        BNavegouSozinhoContaPropria.setVisible(false);
        LabelPreBuraco.setVisible(true);
        BPreBuraco.setVisible(true);
    }//GEN-LAST:event_BNavegouSozinhoContaPropriaActionPerformed

    private void BSeguirRotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSeguirRotaActionPerformed
        LabelSeguirRota.setVisible(false);
        BSeguirRota.setVisible(false);
        LabelPreBuraco.setVisible(true);
        BPreBuraco.setVisible(true);
        
        
    }//GEN-LAST:event_BSeguirRotaActionPerformed

    private void BPreBuracoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPreBuracoActionPerformed
        LabelPreBuraco.setVisible(false);
        BPreBuraco.setVisible(false);
        LabelEntrandoNoBuraco.setVisible(true);
        BEntrandoNoBuraco.setVisible(true);
    }//GEN-LAST:event_BPreBuracoActionPerformed

    private void BEntrandoNoBuracoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEntrandoNoBuracoActionPerformed
        LabelEntrandoNoBuraco.setVisible(false);
        BEntrandoNoBuraco.setVisible(false);
        LabelDecisaoDePlanetas.setVisible(true);
        BDecisaoDePlanetasAzul.setVisible(true);
        BDecisaoDePlanetasLaranja.setVisible(true);
    }//GEN-LAST:event_BEntrandoNoBuracoActionPerformed

    private void BDecisaoDePlanetasLaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDecisaoDePlanetasLaranjaActionPerformed
        LabelDecisaoDePlanetas.setVisible(false);
        BDecisaoDePlanetasAzul.setVisible(false);
        BDecisaoDePlanetasLaranja.setVisible(false);
        LabelEntrarNoPlanetaLaranja.setVisible(true);
        BEntrarNoPlanetaLaranja.setVisible(true);
    }//GEN-LAST:event_BDecisaoDePlanetasLaranjaActionPerformed

    private void BTentaculosEnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTentaculosEnomeActionPerformed
        LabelTentaculosEnormes.setVisible(false);
        BTentaculosEnome.setVisible(false);
        Label1NossosComputadores.setVisible(true);
        BNossosComputadores.setVisible(true);
    }//GEN-LAST:event_BTentaculosEnomeActionPerformed

    private void BEntrarNoPlanetaLaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEntrarNoPlanetaLaranjaActionPerformed
        LabelEntrarNoPlanetaLaranja.setVisible(false);
        BEntrarNoPlanetaLaranja.setVisible(false);
        LabelTentaculosEnormes.setVisible(true);
        BTentaculosEnome.setVisible(true);
    }//GEN-LAST:event_BEntrarNoPlanetaLaranjaActionPerformed

    private void BDecisaoDePlanetasAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDecisaoDePlanetasAzulActionPerformed
        LabelDecisaoDePlanetas.setVisible(false);
        BDecisaoDePlanetasAzul.setVisible(false);
        BDecisaoDePlanetasLaranja.setVisible(false);
        LabelEntrandoPlanetaAzul.setVisible(true);
        BEntrandoPlanetaAzul.setVisible(true);
       
    }//GEN-LAST:event_BDecisaoDePlanetasAzulActionPerformed

    private void BSaindoDaNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSaindoDaNaveActionPerformed
        
        LabelSaindoDaNave.setVisible(false);
        BSaindoDaNave.setVisible(false);
        LabelCivilizacao.setVisible(true);
        BCivilizacao.setVisible(true);
    }//GEN-LAST:event_BSaindoDaNaveActionPerformed

    private void BAbracosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAbracosActionPerformed
        LabelAbracos.setVisible(false);
        BAbracos.setVisible(false);
        LabelumHomem.setVisible(true);
        BumHomem.setVisible(true);
    }//GEN-LAST:event_BAbracosActionPerformed

    private void BCivilizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCivilizacaoActionPerformed
        LabelCivilizacao.setVisible(false);
        BCivilizacao.setVisible(false);
        LabelAbracos.setVisible(true);
        BAbracos.setVisible(true);
    }//GEN-LAST:event_BCivilizacaoActionPerformed

    private void BumHomemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BumHomemActionPerformed
        LabelumHomem.setVisible(false);
        BumHomem.setVisible(false);
        LabelQualONome.setVisible(true);
        BQualONome.setVisible(true);
    }//GEN-LAST:event_BumHomemActionPerformed

    private void BQualONomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BQualONomeActionPerformed
        LabelQualONome.setVisible(false);
        BQualONome.setVisible(false);
        LabelProposta.setVisible(true);
        BProposta.setVisible(true);
        
    }//GEN-LAST:event_BQualONomeActionPerformed

    private void BPropostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPropostaActionPerformed
        LabelProposta.setVisible(false);
        BProposta.setVisible(false);
        LabelAceitarOuRecusar.setVisible(true);
        BAceitar.setVisible(true);
        BRecusar.setVisible(true);
    }//GEN-LAST:event_BPropostaActionPerformed

    private void BAceitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAceitarActionPerformed
        LabelAceitarOuRecusar.setVisible(false);
        BAceitar.setVisible(false);
        BRecusar.setVisible(false);
        LabelPreFim.setVisible(true);
        BPreFim.setVisible(true);
        
    }//GEN-LAST:event_BAceitarActionPerformed

    private void BPreFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPreFimActionPerformed
        LabelPreFim.setVisible(false);
        BPreFim.setVisible(false);
        LabelFicarPlaneta.setVisible(true);
        BFinalFicarPlaneta.setVisible(true);
    }//GEN-LAST:event_BPreFimActionPerformed

    private void BFinalFicarPlanetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFinalFicarPlanetaActionPerformed
        LabelFicarPlaneta.setVisible(false);
        BFinalFicarPlaneta.setVisible(false);
        SelecaoHistoria select = new SelecaoHistoria ();
        JogoDao jDao = new JogoDao ();
        jDao.salvarHistorico(usuario, 9);
        select.setUsuario(usuario);
        select.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BFinalFicarPlanetaActionPerformed

    private void BRecusarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRecusarActionPerformed
        LabelAceitarOuRecusar.setVisible(false);
        BAceitar.setVisible(false);
        BRecusar.setVisible(false);
        LabelRecusarOferta.setVisible(true);
        BRecusarOferta.setVisible(true);
    }//GEN-LAST:event_BRecusarActionPerformed

    private void BRecusarOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRecusarOfertaActionPerformed
        LabelRecusarOferta.setVisible(false);
        BRecusarOferta.setVisible(false);
        LabelAjudaConsertar.setVisible(true);
        BAjudaConsertar.setVisible(true);
    }//GEN-LAST:event_BRecusarOfertaActionPerformed

    private void BAjudaConsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAjudaConsertarActionPerformed
        LabelAjudaConsertar.setVisible(false);
        BAjudaConsertar.setVisible(false);
        LabelCoordenadasOuPaz.setVisible(true);
        BCoordenadas.setVisible(true);
        BDeixaremPaz.setVisible(true);
    }//GEN-LAST:event_BAjudaConsertarActionPerformed

    private void BCoordenadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCoordenadasActionPerformed
        LabelCoordenadasOuPaz.setVisible(false);
        BCoordenadas.setVisible(false);
        BDeixaremPaz.setVisible(false);
        LabelCTE.setVisible(true);
        BCTE.setVisible(true);
    }//GEN-LAST:event_BCoordenadasActionPerformed

    private void BFinalGenocidioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFinalGenocidioActionPerformed
        LabelFinalGenocidio.setVisible(false);
        BFinalGenocidio.setVisible(false);
        SelecaoHistoria selecao = new SelecaoHistoria();
        JogoDao jDao = new JogoDao ();
        jDao.salvarHistorico(usuario, 10);
        
        selecao.setUsuario(usuario);
        selecao.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BFinalGenocidioActionPerformed

    private void BMeChamoEdgarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMeChamoEdgarActionPerformed
        LabelCTE.setVisible(false);
        BCTE.setVisible(false);
        LabelFinalGenocidio.setVisible(true);
        BFinalGenocidio.setVisible(true);
        
    }//GEN-LAST:event_BMeChamoEdgarActionPerformed

    private void BDeixaremPazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDeixaremPazActionPerformed
        LabelCoordenadasOuPaz.setVisible(false);
        BCoordenadas.setVisible(false);
        BDeixaremPaz.setVisible(false);
        LabelOphelia.setVisible(true);
        BOphelia.setVisible(true);
    }//GEN-LAST:event_BDeixaremPazActionPerformed

    private void BOpheliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOpheliaActionPerformed
        LabelOphelia.setVisible(false);
        BOphelia.setVisible(false);
        LabelFimSolitario.setVisible(true);
        BFimSolitario.setVisible(true);
    }//GEN-LAST:event_BOpheliaActionPerformed

    private void BFimSolitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFimSolitarioActionPerformed
        LabelFimSolitario.setVisible(false);
        BFimSolitario.setVisible(false);
        SelecaoHistoria selecao = new SelecaoHistoria();
        JogoDao jDao = new JogoDao ();
        jDao.salvarHistorico(usuario, 11);
        selecao.setUsuario(usuario);
        selecao.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BFimSolitarioActionPerformed

    private void BEntrandoPlanetaAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEntrandoPlanetaAzulActionPerformed
        BEntrandoPlanetaAzul.setVisible(false);
        LabelEntrandoPlanetaAzul.setVisible(false);
        BSaindoDaNave.setVisible(true);
        LabelSaindoDaNave.setVisible(true);
    }//GEN-LAST:event_BEntrandoPlanetaAzulActionPerformed
    public void setUsuario ( Usuario usuario){
        this.usuario = usuario;
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAbracos;
    private javax.swing.JButton BAceitar;
    private javax.swing.JButton BAjudaConsertar;
    private javax.swing.JButton BCTE;
    private javax.swing.JButton BCivilizacao;
    private javax.swing.JButton BCoordenadas;
    private javax.swing.JButton BDecisaoDePlanetasAzul;
    private javax.swing.JButton BDecisaoDePlanetasLaranja;
    private javax.swing.JButton BDeixaremPaz;
    private javax.swing.JButton BEntrandoNoBuraco;
    private javax.swing.JButton BEntrandoPlanetaAzul;
    private javax.swing.JButton BEntrarNoPlanetaLaranja;
    private javax.swing.JButton BFimDesistir;
    private javax.swing.JButton BFimSolitario;
    private javax.swing.JButton BFinalFicarPlaneta;
    private javax.swing.JButton BFinalGenocidio;
    private javax.swing.JButton BInicio1Pagrafo;
    private javax.swing.JButton BMeChamoEdgar;
    private javax.swing.JButton BMudardeIdeia;
    private javax.swing.JButton BNao1Pergunta;
    private javax.swing.JButton BNavegarPorContaPropria;
    private javax.swing.JButton BNavegouSozinhoContaPropria;
    private javax.swing.JButton BNossosComputadores;
    private javax.swing.JButton BOlaRecruta;
    private javax.swing.JButton BOphelia;
    private javax.swing.JButton BPreBuraco;
    private javax.swing.JButton BPreFim;
    private javax.swing.JButton BProposta;
    private javax.swing.JButton BQualONome;
    private javax.swing.JButton BRecusar;
    private javax.swing.JButton BRecusarOferta;
    private javax.swing.JButton BRetornarHistoria;
    private javax.swing.JButton BSaindoDaNave;
    private javax.swing.JButton BSeguirRota;
    private javax.swing.JButton BSeguiraRota;
    private javax.swing.JButton BSim1Pergunta;
    private javax.swing.JButton BTentaculosEnome;
    private javax.swing.JButton BVoltarSelecaoHistoria;
    private javax.swing.JButton BumHomem;
    private javax.swing.JLabel Label1NossosComputadores;
    private javax.swing.JLabel LabelAbracos;
    private javax.swing.JLabel LabelAceitarOuRecusar;
    private javax.swing.JLabel LabelAjudaConsertar;
    private javax.swing.JLabel LabelCTE;
    private javax.swing.JLabel LabelCivilizacao;
    private javax.swing.JLabel LabelCoordenadasOuPaz;
    private javax.swing.JLabel LabelDecisaoDePlanetas;
    private javax.swing.JLabel LabelDesistir;
    private javax.swing.JLabel LabelEntrandoNoBuraco;
    private javax.swing.JLabel LabelEntrandoPlanetaAzul;
    private javax.swing.JLabel LabelEntrarNoPlanetaLaranja;
    private javax.swing.JLabel LabelEsperavaMais;
    private javax.swing.JLabel LabelFicarPlaneta;
    private javax.swing.JLabel LabelFimSolitario;
    private javax.swing.JLabel LabelFinalGenocidio;
    private javax.swing.JLabel LabelInicio1Paragrafo;
    private javax.swing.JLabel LabelInicio1Pergunta;
    private javax.swing.JLabel LabelMeChamoEdgar;
    private javax.swing.JLabel LabelMudoudeIdeia;
    private javax.swing.JLabel LabelNavegarContaPropria;
    private javax.swing.JLabel LabelOlaRecruta;
    private javax.swing.JLabel LabelOphelia;
    private javax.swing.JLabel LabelPreBuraco;
    private javax.swing.JLabel LabelPreFim;
    private javax.swing.JLabel LabelProposta;
    private javax.swing.JLabel LabelQualONome;
    private javax.swing.JLabel LabelRecusarOferta;
    private javax.swing.JLabel LabelSaindoDaNave;
    private javax.swing.JLabel LabelSeguirRota;
    private javax.swing.JLabel LabelSeguirRotaOuNavegar;
    private javax.swing.JLabel LabelTentaculosEnormes;
    private javax.swing.JLabel LabelumHomem;
    // End of variables declaration//GEN-END:variables
}
