/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import com.sun.glass.events.KeyEvent;
import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import musicas.Musica;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import projeto.JogoDao;
import tiposDeLetras.FontManager;

/**
 *
 * @author ewert
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
         
    public Login() {
        
        
        
        initComponents();
           
        
        this.setExtendedState(Login.MAXIMIZED_BOTH);
        
   
    }
   
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CampoLogin = new javax.swing.JTextField();
        CampoSenha = new javax.swing.JPasswordField();
        LabelLogin = new javax.swing.JLabel();
        BotaoLogin = new javax.swing.JButton();
        BotaoSair = new javax.swing.JButton();
        BotaoCadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        CampoLogin.setBackground(new java.awt.Color(255,255,255,0));
        CampoLogin.setFont(new java.awt.Font("Charlemagne Std", 0, 18)); // NOI18N
        CampoLogin.setForeground(new java.awt.Color(255, 255, 255));
        CampoLogin.setBorder(null);
        CampoLogin.setOpaque(false);
        getContentPane().add(CampoLogin);
        CampoLogin.setBounds(370, 330, 540, 60);

        CampoSenha.setBackground(new java.awt.Color(255,255,255,0)
        );
        CampoSenha.setFont(new java.awt.Font("Charlemagne Std", 0, 18)); // NOI18N
        CampoSenha.setForeground(new java.awt.Color(255, 255, 255));
        CampoSenha.setBorder(null);
        CampoSenha.setOpaque(false);
        getContentPane().add(CampoSenha);
        CampoSenha.setBounds(370, 500, 540, 60);

        LabelLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Tela-de-Login.gif"))); // NOI18N
        getContentPane().add(LabelLogin);
        LabelLogin.setBounds(0, -180, 1280, 1070);

        BotaoLogin.setText("login");
        BotaoLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoLoginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoLoginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoLoginMouseReleased(evt);
            }
        });
        BotaoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLoginActionPerformed(evt);
            }
        });
        BotaoLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BotaoLoginKeyPressed(evt);
            }
        });
        getContentPane().add(BotaoLogin);
        BotaoLogin.setBounds(510, 630, 250, 50);

        BotaoSair.setText("jButton1");
        BotaoSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoSairMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoSairMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoSairMouseReleased(evt);
            }
        });
        BotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoSair);
        BotaoSair.setBounds(1190, 10, 80, 40);

        BotaoCadastro.setText("Cadastro");
        BotaoCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoCadastroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoCadastroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoCadastroMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoCadastroMouseReleased(evt);
            }
        });
        BotaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoCadastro);
        BotaoCadastro.setBounds(20, 650, 280, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    private void BotaoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLoginActionPerformed
     
        
        String login = CampoLogin.getText();
        String senha = new String(CampoSenha.getPassword());
        
        JogoDao jDAO = new JogoDao();
        
        
        if(jDAO.retornarClientePeloLogin(login)!= null && senha.equals( jDAO.retornarClientePeloLogin(login).getSenha())) {
            Perfil.usuario = jDAO.retornarClientePeloLogin(login);
            
            Perfil perfil = new Perfil();
            
            
            perfil.setVisible(true);
            this.dispose();
        }
        else if (login.equals("admin") && senha.equals(("caixa"))){
            Mestre mestre = new Mestre();
            mestre.setVisible(true);
            this.dispose();
        }
        else {
            JOptionPane.showMessageDialog(this, "Usuário não encontrado!");
        }
    }//GEN-LAST:event_BotaoLoginActionPerformed

    private void BotaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroActionPerformed
        Cadastro cadastro = new Cadastro ();
        cadastro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotaoCadastroActionPerformed

    private void BotaoLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BotaoLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){    
            String login = CampoLogin.getText();
            String senha = new String(CampoSenha.getPassword());

            JogoDao jDAO = new JogoDao();


            if(jDAO.retornarClientePeloLogin(login)!= null && senha.equals( jDAO.retornarClientePeloLogin(login).getSenha())) {
                Perfil.usuario = jDAO.retornarClientePeloLogin(login);

                Perfil perfil = new Perfil();


                perfil.setVisible(true);
                this.dispose();
            }
            else {
                JOptionPane.showMessageDialog(this, "Usuário não encontrado!");
            }
        }
    }//GEN-LAST:event_BotaoLoginKeyPressed

    private void BotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotaoSairActionPerformed

    private void BotaoLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoLoginMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotaoLoginMouseEntered

    private void BotaoLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoLoginMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoLoginMouseExited

    private void BotaoLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoLoginMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoLoginMousePressed

    private void BotaoLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoLoginMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoLoginMouseReleased

    private void BotaoSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoSairMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotaoSairMouseEntered

    private void BotaoSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoSairMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoSairMouseExited

    private void BotaoSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoSairMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoSairMousePressed

    private void BotaoSairMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoSairMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoSairMouseReleased

    private void BotaoCadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoCadastroMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotaoCadastroMouseEntered

    private void BotaoCadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoCadastroMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoCadastroMouseExited

    private void BotaoCadastroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoCadastroMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoCadastroMousePressed

    private void BotaoCadastroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoCadastroMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoCadastroMouseReleased
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastro;
    private javax.swing.JButton BotaoLogin;
    private javax.swing.JButton BotaoSair;
    private javax.swing.JTextField CampoLogin;
    private javax.swing.JPasswordField CampoSenha;
    private javax.swing.JLabel LabelLogin;
    // End of variables declaration//GEN-END:variables

    
}
