/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Cursor;
import javax.swing.JOptionPane;
import projeto.JogoDao;

/**
 *
 * @author ewert
 */
public class Mestre extends javax.swing.JFrame {

    /**
     * Creates new form Mestre
     */
    public Mestre() {
        initComponents();
         this.setExtendedState(Mestre.MAXIMIZED_BOTH);
        
        CampoExibir.setText("\n"+"\n"+"\n");
        JogoDao jdao = new JogoDao ();
        int x = jdao.listarOpinioes().size();
        
        
        
        for(int i =(x-1);i >=0;i--){
            CampoExibir.setText(CampoExibir.getText()+jdao.listarOpinioes().get(i)+"\n");
        }
    
        LabelSetaPressionado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelAvaliacoes = new javax.swing.JLabel();
        BotaoCadastro = new javax.swing.JLabel();
        CampoExibir = new javax.swing.JTextArea();
        LabelSetaPressionado = new javax.swing.JLabel();
        LabelMestre = new javax.swing.JLabel();
        BotaoClicarAvaliacoes = new javax.swing.JButton();
        BotaoReturn = new javax.swing.JButton();
        BotaoClicarCadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        LabelAvaliacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BotaoAvaliacoesFeedBack.png"))); // NOI18N
        getContentPane().add(LabelAvaliacoes);
        LabelAvaliacoes.setBounds(250, 630, 730, 50);

        BotaoCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BotaoCadastroFeedBack.png"))); // NOI18N
        getContentPane().add(BotaoCadastro);
        BotaoCadastro.setBounds(-280, 620, 740, 80);

        CampoExibir.setEditable(false);
        CampoExibir.setBackground(new java.awt.Color(255,255,255,0));
        CampoExibir.setColumns(20);
        CampoExibir.setFont(new java.awt.Font("Charlemagne Std", 0, 18)); // NOI18N
        CampoExibir.setForeground(new java.awt.Color(255, 255, 255));
        CampoExibir.setRows(5);
        CampoExibir.setBorder(null);
        CampoExibir.setOpaque(false);
        getContentPane().add(CampoExibir);
        CampoExibir.setBounds(90, 160, 1100, 450);

        LabelSetaPressionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta tela mestre.png"))); // NOI18N
        getContentPane().add(LabelSetaPressionado);
        LabelSetaPressionado.setBounds(0, 0, 630, 720);

        LabelMestre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela-mestre-fixed.gif"))); // NOI18N
        getContentPane().add(LabelMestre);
        LabelMestre.setBounds(0, 0, 1280, 720);

        BotaoClicarAvaliacoes.setText("jButton1");
        BotaoClicarAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoClicarAvaliacoesActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoClicarAvaliacoes);
        BotaoClicarAvaliacoes.setBounds(740, 640, 240, 23);

        BotaoReturn.setText("jButton1");
        BotaoReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoReturnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoReturnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoReturnMouseReleased(evt);
            }
        });
        BotaoReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoReturnActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoReturn);
        BotaoReturn.setBounds(10, 30, 73, 60);

        BotaoClicarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoClicarCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoClicarCadastro);
        BotaoClicarCadastro.setBounds(250, 640, 210, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoReturnActionPerformed
        Login login = new Login ();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoReturnActionPerformed

    private void BotaoReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotaoReturnMouseEntered

    private void BotaoReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoReturnMouseExited

    private void BotaoReturnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMousePressed
        LabelSetaPressionado.setVisible(true);
    }//GEN-LAST:event_BotaoReturnMousePressed

    private void BotaoReturnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMouseReleased
        LabelSetaPressionado.setVisible(false);
    }//GEN-LAST:event_BotaoReturnMouseReleased

    private void BotaoClicarAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoClicarAvaliacoesActionPerformed
        ExibirAvaliacoes avaliacoes = new ExibirAvaliacoes ();
        avaliacoes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoClicarAvaliacoesActionPerformed

    private void BotaoClicarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoClicarCadastroActionPerformed
       ExibirCadastros cadastros = new ExibirCadastros ();
       cadastros.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BotaoClicarCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotaoCadastro;
    private javax.swing.JButton BotaoClicarAvaliacoes;
    private javax.swing.JButton BotaoClicarCadastro;
    private javax.swing.JButton BotaoReturn;
    private javax.swing.JTextArea CampoExibir;
    private javax.swing.JLabel LabelAvaliacoes;
    private javax.swing.JLabel LabelMestre;
    private javax.swing.JLabel LabelSetaPressionado;
    // End of variables declaration//GEN-END:variables
}
