 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Cursor;
import java.util.Date;
import projeto.JogoDao;
import projeto.Usuario;


/**
 *
 * @author ewert
 */
public class Opiniao extends javax.swing.JFrame {
    private Usuario usuario;
    /**
     * Creates new form Opiniao
     */
    public Opiniao() {
        initComponents();
        this.setExtendedState(Opiniao.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CaixaOpiniao = new javax.swing.JTextArea();
        LabelOpinar = new javax.swing.JLabel();
        BotaoReturn = new javax.swing.JButton();
        BotaoOpinar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        CaixaOpiniao.setBackground(new java.awt.Color(255,255,255,0)
        );
        CaixaOpiniao.setColumns(20);
        CaixaOpiniao.setFont(new java.awt.Font("Charlemagne Std", 0, 18)); // NOI18N
        CaixaOpiniao.setForeground(new java.awt.Color(255, 255, 255));
        CaixaOpiniao.setLineWrap(true);
        CaixaOpiniao.setRows(5);
        CaixaOpiniao.setToolTipText("");
        CaixaOpiniao.setWrapStyleWord(true);
        CaixaOpiniao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        CaixaOpiniao.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CaixaOpiniao.setOpaque(false);
        getContentPane().add(CaixaOpiniao);
        CaixaOpiniao.setBounds(50, 70, 1180, 520);

        LabelOpinar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela-de-opiniao.gif"))); // NOI18N
        getContentPane().add(LabelOpinar);
        LabelOpinar.setBounds(0, 0, 1272, 720);

        BotaoReturn.setText("jButton1");
        BotaoReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoReturnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoReturnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoReturnMouseReleased(evt);
            }
        });
        BotaoReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoReturnActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoReturn);
        BotaoReturn.setBounds(20, 650, 73, 60);

        BotaoOpinar.setText("jButton1");
        BotaoOpinar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoOpinarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoOpinarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoOpinarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoOpinarMouseReleased(evt);
            }
        });
        BotaoOpinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoOpinarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoOpinar);
        BotaoOpinar.setBounds(440, 620, 410, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoReturnActionPerformed
        Perfil perfil = new Perfil ();
        perfil.setUsuario(usuario);
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoReturnActionPerformed

    private void BotaoOpinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoOpinarActionPerformed
        JogoDao jdao = new JogoDao ();
        Date date = new Date ();
        jdao.salvarOpiniao(usuario, CaixaOpiniao.getText() );
        
    }//GEN-LAST:event_BotaoOpinarActionPerformed

    private void BotaoReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotaoReturnMouseEntered

    private void BotaoReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoReturnMouseExited

    private void BotaoReturnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoReturnMousePressed

    private void BotaoReturnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoReturnMouseReleased

    private void BotaoOpinarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoOpinarMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotaoOpinarMouseEntered

    private void BotaoOpinarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoOpinarMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoOpinarMouseExited

    private void BotaoOpinarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoOpinarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoOpinarMousePressed

    private void BotaoOpinarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoOpinarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoOpinarMouseReleased
    
    public void setUsuario(Usuario usuario){
        this.usuario = usuario;
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoOpinar;
    private javax.swing.JButton BotaoReturn;
    private javax.swing.JTextArea CaixaOpiniao;
    private javax.swing.JLabel LabelOpinar;
    // End of variables declaration//GEN-END:variables
}
