/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Cursor;
import javax.swing.JOptionPane;
import projeto.Usuario;

/**
 *
 * @author ewert
 */
public class Sinopse extends javax.swing.JFrame {

    private Usuario usuario;

    /**
     * Creates new form Sinopse
     */
    public Sinopse() {
        initComponents();
         this.setExtendedState(Sinopse.MAXIMIZED_BOTH);
        LabelBarPressionado.setVisible(false);
        LabelSetaPressionado.setVisible(false);
        LabelEspacoPressionado.setVisible(false);
        LabelFarolPressionado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelEspacoPressionado = new javax.swing.JLabel();
        LabelFarolPressionado = new javax.swing.JLabel();
        LabelBarPressionado = new javax.swing.JLabel();
        LabelSetaPressionado = new javax.swing.JLabel();
        LabelSinopse = new javax.swing.JLabel();
        BotaoReturn = new javax.swing.JButton();
        BotaoEspaco = new javax.swing.JButton();
        BotaoBar = new javax.swing.JButton();
        BotaoFarol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        LabelEspacoPressionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao espaco tela sinopse.png"))); // NOI18N
        LabelEspacoPressionado.setText("jLabel1");
        LabelEspacoPressionado.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(LabelEspacoPressionado);
        LabelEspacoPressionado.setBounds(0, 60, 470, 600);

        LabelFarolPressionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao farol tela sinopse.png"))); // NOI18N
        LabelFarolPressionado.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(LabelFarolPressionado);
        LabelFarolPressionado.setBounds(0, 0, 1280, 720);

        LabelBarPressionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao bar tela sinopse.png"))); // NOI18N
        LabelBarPressionado.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(LabelBarPressionado);
        LabelBarPressionado.setBounds(0, 0, 1280, 720);

        LabelSetaPressionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta tela sinopse.png"))); // NOI18N
        LabelSetaPressionado.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(LabelSetaPressionado);
        LabelSetaPressionado.setBounds(0, 0, 1190, 720);

        LabelSinopse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela-sinopse-fixed.gif"))); // NOI18N
        getContentPane().add(LabelSinopse);
        LabelSinopse.setBounds(0, 0, 1280, 720);

        BotaoReturn.setText("jButton2");
        BotaoReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoReturnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoReturnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoReturnMouseReleased(evt);
            }
        });
        BotaoReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoReturnActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoReturn);
        BotaoReturn.setBounds(3, 650, 80, 60);

        BotaoEspaco.setText("jButton1");
        BotaoEspaco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoEspacoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoEspacoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoEspacoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoEspacoMouseReleased(evt);
            }
        });
        BotaoEspaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEspacoActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEspaco);
        BotaoEspaco.setBounds(50, 110, 340, 540);

        BotaoBar.setText("jButton3");
        BotaoBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoBarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoBarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoBarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoBarMouseReleased(evt);
            }
        });
        BotaoBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoBar);
        BotaoBar.setBounds(460, 113, 340, 560);

        BotaoFarol.setText("jButton4");
        BotaoFarol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoFarolMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoFarolMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoFarolMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoFarolMouseReleased(evt);
            }
        });
        BotaoFarol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFarolActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoFarol);
        BotaoFarol.setBounds(890, 113, 330, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBarActionPerformed
        JOptionPane.showMessageDialog(this, "Infelizmente este jogo não possui essa historia ainda, pois estamos desenvolvendo... Jogue as outras");
    }//GEN-LAST:event_BotaoBarActionPerformed

    private void BotaoBarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBarMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotaoBarMouseEntered

    private void BotaoBarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBarMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoBarMouseExited

    private void BotaoBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBarMousePressed
        LabelBarPressionado.setVisible(true);
    }//GEN-LAST:event_BotaoBarMousePressed

    private void BotaoBarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBarMouseReleased
        LabelBarPressionado.setVisible(false);
    }//GEN-LAST:event_BotaoBarMouseReleased

    private void BotaoEspacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEspacoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoEspacoActionPerformed

    private void BotaoReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoReturnActionPerformed
        SelecaoHistoria selecaohistoria = new SelecaoHistoria();
        selecaohistoria.setUsuario(usuario);
        selecaohistoria.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoReturnActionPerformed

    private void BotaoFarolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFarolActionPerformed
        JogoFarol farol = new JogoFarol ();
        farol.setVisible(true);
        farol.setUsuario(usuario);
        this.dispose();
    }//GEN-LAST:event_BotaoFarolActionPerformed

    private void BotaoReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotaoReturnMouseEntered

    private void BotaoReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoReturnMouseExited

    private void BotaoReturnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMousePressed
        LabelSetaPressionado.setVisible(true);
    }//GEN-LAST:event_BotaoReturnMousePressed

    private void BotaoReturnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoReturnMouseReleased
        LabelSetaPressionado.setVisible(false);
    }//GEN-LAST:event_BotaoReturnMouseReleased

    private void BotaoEspacoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEspacoMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotaoEspacoMouseEntered

    private void BotaoEspacoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEspacoMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoEspacoMouseExited

    private void BotaoEspacoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEspacoMousePressed
        LabelEspacoPressionado.setVisible(true);
    }//GEN-LAST:event_BotaoEspacoMousePressed

    private void BotaoEspacoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEspacoMouseReleased
        LabelEspacoPressionado.setVisible(false);
    }//GEN-LAST:event_BotaoEspacoMouseReleased

    private void BotaoFarolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoFarolMouseEntered
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
       setCursor(handCursor);
    }//GEN-LAST:event_BotaoFarolMouseEntered

    private void BotaoFarolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoFarolMouseExited
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(defaultCursor);
    }//GEN-LAST:event_BotaoFarolMouseExited

    private void BotaoFarolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoFarolMousePressed
        LabelFarolPressionado.setVisible(true);
    }//GEN-LAST:event_BotaoFarolMousePressed

    private void BotaoFarolMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoFarolMouseReleased
        LabelFarolPressionado.setVisible(false);
    }//GEN-LAST:event_BotaoFarolMouseReleased
    
    public void setUsuario (Usuario usuario){
        this.usuario = usuario;
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoBar;
    private javax.swing.JButton BotaoEspaco;
    private javax.swing.JButton BotaoFarol;
    private javax.swing.JButton BotaoReturn;
    private javax.swing.JLabel LabelBarPressionado;
    private javax.swing.JLabel LabelEspacoPressionado;
    private javax.swing.JLabel LabelFarolPressionado;
    private javax.swing.JLabel LabelSetaPressionado;
    private javax.swing.JLabel LabelSinopse;
    // End of variables declaration//GEN-END:variables
}
